### ISSUE TITLE
OCI Route table module need update to support the route for the service gateway

### ISSUE THREAD

**Issue by neerkuma** [oracle/oci-ansible-modules#10]
A clear and concise description of what the issue is.

At this point in oci_route_table module under the route rules only have the option cidr_block and does not show any option of the service in the documentation. Either the route table documentation is not updated or the module is still not have the updated to support the service gateway rules for object storage service. let me know if there is  a way to add route rule using oci_route_table module. Also I am facing similar chalanges for the security list to add the security rules for the object storage service. 

Ansible version:

ansible 2.6.4

OCI Python SDK version:

2.0.3

OCI Ansible Modules version:
1.1.0

**Comment by debayan-gupta** [comment]
Thanks for raising this. This feature is not supported as of current release. We'll add this feature in both Route Table and Security list in the upcoming release.

**Comment by neerkuma** [comment]
Hi,

Can you please let me know what is the target date of the upcoming release.

-Neeraj

**Comment by debayan-gupta** [comment]
We'll get back to you by Wednesday with the timeline.

**Comment by debayan-gupta** [comment]
Expect the feature as part of our current release, which is due within this Friday. I'll update this issue with the relase when it is available.

**Comment by sivakumart** [comment]
@neerkuma A new release [1.3.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.3.0) was posted today and this has added this feature. Both `oci_security_list` and `oci_route_table` allows the specification of a `destination_type` while specifying security rules and route table entries. 

Please see
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_security_list_module.html
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_route_table_module.html

Please try out the modules and share any feedback that you may have. Thanks.
