### ISSUE TITLE
The oci_vnic_facts module does not expose the nsg_ids attribute.

### ISSUE THREAD

**Issue by plakdawa** [oracle/oci-ansible-modules#101]
## Issue Report

**Describe the issue**

The `oci_vnic_facts` module does not expose the `nsg_ids` attribute.

**Expected behavior**

Per the latest [OCI python SDK](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.Vnic.html#oci.core.models.Vnic), the vnic resource has `nsg_ids` as an attribute.

Per the latest [ansible modules documentation](https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_vnic_facts_module.html#oci-vnic-facts-module), this attribute is missing in the `oci_vnic_facts` module.

I have not checked if this is merely an oversight in the documentation, or if the attribute is actually missing.

Please confirm and correct appropriately.

**Environment**

* OS version:

* Ansible version:

    insert output of `ansible --version` here

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here

* OCI Ansible Modules version:

    insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by AmeyaLokre** [comment]
Hello @plakdawa , thank you for bringing this to our attention. We will ensure that the `nsg_ids` will be included in the `oci_vnic_facts` module in the coming releases.

**Comment by AmeyaLokre** [comment]
Hello @plakdawa , this bug has been addressed in the new release of oci-ansible-modules.
https://github.com/oracle/oci-ansible-modules/releases/tag/v1.17.0
