### ISSUE TITLE
oci_inventory.py fails with TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mannyreds11** [oracle/oci-ansible-modules#102]
## Issue Report

**Describe the issue**

oci_inventory.py fails with TypeError: 'NoneType' object is not iterable
```
➜  inventory-script git:(master) ✗ ./oci_inventory.py --profile "FRA-EU3-REGSVC" --auth="api_key" --debug
...
Building inventory for instance ocid1.instance.oc1.eu-frankfurt-1.abtheljtoxew52afqs2o5qg7xv4k57imxd5eoasjiax2xhjccabbef6j7q6a
Traceback (most recent call last):
  File "./oci_inventory.py", line 409, in __init__
    self.build_inventory()
  File "./oci_inventory.py", line 1219, in build_inventory
    for instance in instances_by_region[region]
  File "./oci_inventory.py", line 1043, in build_inventory_for_instance
    for key in instance.metadata:
TypeError: 'NoneType' object is not iterable
```
Note: I attempted with `instance_principal` as well. I saw this previous solution: https://github.com/oracle/oci-ansible-modules/issues/54#issuecomment-496401654 but unfortunately I don't have control over permissions on my tenancy. Is there another work-around?

**Expected behavior**

oci_inventory.py should build inventory

**Environment**

* OS version: macOS Mojave (10.14.5)

* Ansible version:

```
➜  inventory-script git:(master) ✗ ansible --version
ansible 2.9.5
  config file = None
  configured module search path = [u'/Users/mrojas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mrojas/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/mrojas/Library/Python/2.7/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

* OCI Python SDK version:
```
➜  inventory-script git:(master) ✗ python -c "import oci;print(oci.__version__)"
2.10.5
```

* OCI Ansible Modules version:

```
➜  inventory-script git:(master) ✗ python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"
1.6.0-dev
```

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by manojmeda** [comment]
@mannyreds11 You could try generating inventory for only the compartments that you have read permission on instances. You can generate inventory for a specific compartment by passing `compartment_ocid` command line argument or by setting `OCI_COMPARTMENT_OCID ` environment variable. Please check https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/dynamic-inventory-script.html for more details.
