### ISSUE TITLE
oci_tag can not set type as list

### ISSUE THREAD

**Issue by lucianoventura** [oracle/oci-ansible-modules#107]
ISSUE no github:

Using the module oci_tag:

There is no way to set "Tag Value Type" as "A LIST OF VALUES" and the built-in default is "string" 

**Expected behavior**

As per api definition:

https://docs.cloud.oracle.com/en-us/iaas/api/#/en/identity/20160918/datatypes/EnumTagDefinitionValidator

We should be able to set a "tag value type" as "list" an provide a list of values

**Environment**
DEV

* OS version:
RHEL 7.7

* Ansible version:

ansible 2.9.3
 

* OCI Python SDK version:

 2.12.4

* OCI Ansible Modules version:

1.6.0-dev

**Comment by AmeyaLokre** [comment]
Hello @lucianoventura , thank you for bringing this to our attention. Right now, the oci ansible-cloud-modules do not support creating tags of with type `list` as mentioned in the [oci ansible docs](https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_tag_module.html).
This feature will be supported in the new collections which will be released soon.

**Comment by lucianoventura** [comment]
I am a ansible heavy user and intend to use these modules in production for OCI, and tags is key feature.

Can I kindly ask you when these features will be available?

**Comment by AmeyaLokre** [comment]
Hello @lucianoventura , thank you for using our oci ansible tool and providing is with your valuable feedback. <br/>
We are planning on releasing the new collections in a month's time. We will notify if there are any schedule changes for this release.

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
