### ISSUE TITLE
oci_tag_facts can not get the list of values when setup as list  

### ISSUE THREAD

**Issue by lucianoventura** [oracle/oci-ansible-modules#108]
Using the module oci_tag_facts:

There is no way to get the list of values when setup as list 

**Expected behavior**

We should be able to get the list of values of a tag when setup as list 

**Environment**
DEV

* OS version:
RHEL 7.7

* Ansible version:

ansible 2.9.3
 

* OCI Python SDK version:

 2.12.4

* OCI Ansible Modules version:

1.6.0-dev

**Comment by AmeyaLokre** [comment]
Hello @lucianoventura , as mentioned in the github issue https://github.com/oracle/oci-ansible-modules/issues/107, the feature to support the tag value type as list will be supported in the new collections which will be released soon.

**Comment by lucianoventura** [comment]
I am a ansible heavy user and intend to use these modules in production for OCI, and tags is key feature.

Can I kindly ask you when these features will be available?

**Comment by AmeyaLokre** [comment]
Hello @lucianoventura , thank you for using our oci ansible tool and providing is with your valuable feedback. <br/>
We are planning on releasing the new collections in a month's time. We will notify if there are any schedule changes for this release.

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
