### ISSUE TITLE
oci_security_list and oci_route_table modules need support for populating the 'description' field

### ISSUE THREAD

**Issue by joshmullis** [oracle/oci-ansible-modules#112]
## Enhancement request

oci_security_list and oci_route_table modules need support for populating the 'description' field of a security rule / route table entry.
These modules currently do not support this, but the option is available via the Web UI.

**Comment by ruturajmolawade** [comment]
Hello @joshmullis, thank you for bringing this to our attention. Right now, oci_security_list & oci_route_table modules do not support an optional field `description`. This feature will be supported in the new collections which will be released soon.

**Comment by nalsaber** [comment]
This feature ( 'description' field) is released now in our new modules: https://github.com/oracle/oci-ansible-collection/
