### ISSUE TITLE
Add public_ip and private_ip to inventory's hostvars section

### ISSUE THREAD

**Issue by vpeltola** [oracle/oci-ansible-modules#114]
## Issue Report

**Describe the issue**

This is a request to add the "public_ip" and "private_ip" attributes to the _meta.hostvars section of the inventory.  This is especially useful when using the --hostname-format=fqdn option with oci_inventory.py.  In certain cases we require this information to set up ssh config entries which allow ansible to ssh into the hosts in the inventory.

oci_inventory.py already queries this data, but does not expose it in the inventory.  This is just a request to expose the data.

**Expected behavior**

Each host has a primary private_ip.  Some hosts also have a public_ip.  Insert the primary private_ip address into each host's hostvars, and if a public IP exists, then insert that as well.

    { 
      "_meta": {
        "hostvars": {
          "myhost.example.com": {
            "private_ip": "100.0.0.1",
            "public_ip": "144.1.1.1",
             ...
          }
        }
      }
    }

The following code added to the build_inventory_for_instance() method shows one possible (but maybe too simple) implementation:

                # Customization to include private_ip and public_ip in hostvars
                if vnic.private_ip:
                    self.log("{0} has private_ip {1}".format(host_name, vnic.private_ip))
                    instance_vars['private_ip'] = vnic.private_ip
                else:
                    self.log("{0} has no private_ip".format(host_name))

                if vnic.public_ip:
                    self.log("{0} has public_ip {1}".format(host_name, vnic.public_ip))
                    instance_vars['public_ip'] = vnic.public_ip
                else:
                    self.log("{0} has no public_ip".format(host_name))

                # Skip host which is not addressable using hostname_format
                if not host_name:

**Environment**
N/A

* OS version:
Generic

* Ansible version:

ansible 2.9.6
  config file = /app/ansible/ansible.cfg
  configured module search path = ['/app/ansible/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 10 2019, 15:33:49) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4.0.1)]

* OCI Python SDK version:

    2.12.2

* OCI Ansible Modules version:

   1.17.0

**Ansible playbook to reproduce the issue**
N/A

**Comment by nalsaber** [comment]
We already do that in the inventory plugin. Did you try that?
https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/ansibledynamicinventoryplugin.htm

**Comment by vpeltola** [comment]
Hi, I have, but it's lacking options that the standalone script has, and for some reason is performing much slower as well (even with multi-threading enabled).  At this point the standalone works much better for me, so it would be great to add these two IP address properties to it, too.

**Comment by nalsaber** [comment]
Thanks for the info. Do you mind creating a PR for the code you provided? We can test it and merge it.
 We were planning to improve the plugin to make it better than the standalone script. It would be useful if you can provide what options are lacking.

**Comment by vpeltola** [comment]
Thank you!  I have created a pull request.  Please review.

**Comment by nalsaber** [comment]
We added this feature in the Inventory Plugin in the latest collection release:
https://github.com/oracle/oci-ansible-collection/releases/tag/v2.8.0
We added these features:
-     queries hosts with public_ip and private ips
-     accept "hostname_format: fqdn"
-     you can enable multiple threads
-     accepts --regions=all

Please make sure that you are using the plugin from the new collection:
https://github.com/oracle/oci-ansible-collection/
