### ISSUE TITLE
Add a --cache-refresh-locking option to oci_inventory.py

### ISSUE THREAD

**Issue by vpeltola** [oracle/oci-ansible-modules#116]
## Issue Report

In a situation where multiple ansible playbook executions are being run at overlapping times, and those ansible instances share the same inventory cache, it would be beneficial to have an option to create a mutually exclusive lock on the cached inventory when it is being refreshed, so that not every instance starts to refresh the cache at the same time when the cache has expired.

This could be an optional feature enabled by a command line option for oci_inventory.py, or a config file option for the inventory plugin. 

**Expected behavior**

When a command line option such as "--cache-refresh-locking" is used when running  oci_inventory.py. then the following should happen.

- oci_inventory.py determines the cache file name (no change from current)
- oci_inventory.py checks if the cached file exists and is valid (no change)
- if the cache is valid, then just proceed to use the cache file as usual
- else, if the cache is invalid, then
  - if the cache-refresh-locking option was used then:
    - try to obtain an mutually exclusive lock on the inventory
    - If lock already exists, wait until lock is cleared
    - when lock is obtained, check if the cache is valid again, in case it was just refreshed by another instance
    - if cache is again invalid, then refresh it and save the cache file
    - release the lock
  - else, if cache-refresh-locking option was not used, just refresh the cache and save the cache file.
- print inventory

Sample python code:

            if not self.args.refresh_cache and self.is_cache_valid():
                self.log(
                    "Reading inventory from cache {0}.".format(
                        self.params["cache_file"]
                    )
                )
                self.inventory = self.read_from_cache()
            else:
                if self.params['cache_refresh_locking']:
                    self.obtain_lock()
                    # Another process might have refreshed the cache while we waited for the lock...
                    if self.is_cache_valid():
                        self.inventory = self.read_from_cache()
                        self.log("Reading inventory from cache {0}.".format(self.params["cache_file"]))
                    else:
                        self.build_inventory()
                        self.write_to_cache(self.inventory)
                    self.remove_lock()
                else:
                    self.build_inventory()
                    self.write_to_cache(self.inventory)

Similar logic could be added to the ansible oci inventory plugin.

**Environment**

* OS version:
Generic

* Ansible version:

ansible 2.9.6
config file = /app/ansible/ansible.cfg
configured module search path = ['/app/ansible/library']
ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.6.8 (default, Nov 10 2019, 15:33:49) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4.0.1)]

* OCI Python SDK version:

 2.12.2

* OCI Ansible Modules version:

1.17.0

**Ansible playbook to reproduce the issue**

  N/A

**Comment by nalsaber** [comment]
Good point. We will evaluate thanks!

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
