### ISSUE TITLE
ER: Extend WAF WAAS policy to support more access rule criteria

### ISSUE THREAD

**Issue by simonhaslam** [oracle/oci-ansible-modules#117]
## Enhancement Request
The oci_waas_policy only supports 13 types of access rule criteria (https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_waas_policy_module.html#oci-waas-policy-module).  However WAF itself now has several (probably relatively new) "NOT" types (https://docs.cloud.oracle.com/en-us/iaas/api/#/en/waas/20181116/datatypes/AccessRuleCriteria)
URL_DOES_NOT_MATCH_REGEX
URL_DOES_NOT_START_WITH
URL_PART_DOES_NOT_CONTAIN
URL_PART_DOES_NOT_END_WITH
(plus header/method ones for which the ansible module offers user agent)

**Expected behavior**

We would like the ansible module to support some or all of these new types so that we can set up block rules based on URL patterns. It seems relatively easy to add these extra choices as they seem to be passed straight though to the OCI API & we have what seems to be a working example.

**Environment**
* OCI Ansible Modules version:
1.18

**Comment by simonhaslam** [comment]
My colleague Colin has made a change in https://github.com/eProseed/oci-ansible-modules/tree/er117-waf-waas-policy which we are just testing - should be ready for PR soon.

**Comment by nalsaber** [comment]
Great we will review that PR and merge it. Thx!

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
