### ISSUE TITLE
ER: Extend to Health Checks 

### ISSUE THREAD

**Issue by simonhaslam** [oracle/oci-ansible-modules#118]
## Enhancement Request
We would like to use Ansible to set up Health Checks (https://docs.cloud.oracle.com/en-us/iaas/Content/HealthChecks/Concepts/healthchecks.htm) for future environments.  For us it's not yet a definite requirement but the feature looks useful and could replace alternative methods. At the moment there's nothing in the Ansible module for them.

**Expected behavior**
Even a partial implentation of the API (https://docs.cloud.oracle.com/en-us/iaas/api/#/en/healthchecks/20180501/) would be useful. For me the priorities would be:
1. to be able to create/delete monitors (HTTP primarily)
2. to disable healthcheck & reenable it again (e.g. maintenance windows)
On-demand probes are not too important to me since i'm looking for "always-on" monitoring. Retrieving data would be less important too since that would probably be done by a different methods (e.g. OCI monitoring/alarms on the metrics).

**Environment**
* OCI Ansible Modules version:
1.18

**Comment by nalsaber** [comment]
The health check service will be available within 2 weeks in the new collections repo. We will notify you with the details once it is ready.

**Comment by nalsaber** [comment]
We are excited to announce the beta launch of [New OCI Ansible Collection](https://github.com/oracle/oci-ansible-collection). They have the health check service.
