### ISSUE TITLE
Enable oci-ansible-modules to be installable via pip

### ISSUE THREAD

**Issue by dmitrypol** [oracle/oci-ansible-modules#12]
This project is very interesting and thank you for creating it.  But using the code from github makes it harder to distribute.  It would be nice if it were available via https://pypi.org/.  Or least installable directly from github via pip.  

Running
```
pipenv install -e git+https://github.com/oracle/oci-ansible-modules.git@v1.3.0#egg=oci-ansible-modules
```
Failed with
```
    FileNotFoundError: [Errno 2] No such file or directory: '.../.local/share/virtualenvs/.../src/oci-ansible-modules/setup.py'
```
because there is no setup.py

**Comment by sivakumart** [comment]
Thanks @dmitrypol for your kind words and ideas.

Our goal is to get the modules integrated into the [Ansible Module index](https://docs.ansible.com/ansible/latest/modules/modules_by_category.html) and work is ongoing on it. Once that is done, the recommended way to get the modules would through official Ansible releases. The current mechanism of using an installer script was just a temporary work-around.

We are also evaluating other standard packaging ways by which users can get access to these modules.

To make the developer installation usecase easier, as you suggest, we will atleast work on getting pip based repo installs possible. (PyPI based installs may not be needed if we have the other mechanisms in place).

**Comment by arnoschots** [comment]
+1 for the idea. fully agree

**Comment by koaps** [comment]
+1 also agree, though having the module in Ansible module index would be great

**Comment by nalsaber** [comment]
We are working on including our modules with AMI but it will take some time.
One option for installation is to use Ansible Galaxy: https://galaxy.ansible.com/oracle/oci_ansible_modules

**Comment by nalsaber** [comment]
The new modules can be easily installed now using  collections https://github.com/oracle/oci-ansible-collection/t
