### ISSUE TITLE
Create an official Ansible Collection

### ISSUE THREAD

**Issue by mhalano** [oracle/oci-ansible-modules#120]
## Issue Report

**Describe the issue**

Ansible is migration core parts of its code to collections, a group from resources related to a technology, like Kubernetes, for instance.

**Expected behavior**

A collection maybe called "oracle.oci" can be imported to be used on playbooks by users and should contain both modules as plugins.

**Comment by nalsaber** [comment]
We are actually working on that it should be out within a week. 
https://github.com/oracle/oci-ansible-collections/

**Comment by nalsaber** [comment]
We are excited to announce the beta launch of [New OCI Ansible Collection](https://github.com/oracle/oci-ansible-collection).
