### ISSUE TITLE
Inventory script doesn't pull DBaaS VM hosts

### ISSUE THREAD

**Issue by RupinderWalia** [oracle/oci-ansible-modules#123]
## Issue Report
Dynamic Inventory script doesn't pull DBaaS VM hosts and VM hosts in ManagedCompartmentforPAAS (OCI built- in compartment)

**Describe the issue**
We have latest dynamic inventory script and ini file. Config file is set with API keys and we can see most of compute resources while using dynamic inventory script.
We have Compute VM instances in ManagedCompartmentforPaas for SOA Cloud Service. We also have separate DBaaS VMs in multiple compartments that we have manage access on. We basically have the administrator access on entire tenancy. The Dynamic inventory script doesn't pull the DBaaS and ManagedCompartmentforPaas VMs

A clear and concise description of what the issue is.

**Expected behavior**
Like to see all the Compute VM and DBaaS VMs

**Environment**
OCI
* OS version:
CentOS 7.4
* Ansible version:

    insert output of `ansible --version` here
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/venv/ps-oci/lib/python3.6/site-packages/ansible,/usr/share/ansible/plugins/modules,/var/lib/awx/venv/ps-oci/oci-ansible-modules']
  ansible python module location = /var/lib/awx/venv/ps-oci/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ps-oci/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

* OCI Ansible Modules version:

    insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here
1.6.0-dev

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by RupinderWalia** [comment]
Hello, 

Is anyone looking at it?

Thanks

**Comment by AmeyaLokre** [comment]
Hello @RupinderWalia , apologies for the delay. 
We are looking into the issue and will let you know with a resolution or if any more info is needed.

**Comment by AmeyaLokre** [comment]
Hello @RupinderWalia , this is a feature that we do not support ye. We will add this feature to our future feature lists to work on and will notify on this issue once it is available. Thank you for your patience.

**Comment by RupinderWalia** [comment]
Thanks Ameya. Looking forward to hearing on this

**Comment by revnav** [comment]
Thanks Guys. We need this too. Using dynamic inventory for our patching, startup shutdown etc. This will be really helpful.

**Comment by tyskjohan** [comment]
+1

**Comment by nalsaber** [comment]
We added this feature in the Inventory Plugin in the latest collection release:
https://github.com/oracle/oci-ansible-collection/releases/tag/v2.8.0

Please make sure that you are using the plugin from the new collection:
https://github.com/oracle/oci-ansible-collection/

https://github.com/oracle/oci-ansible-collection/blob/v2.8.0/plugins/inventory/oci.py
In the plugin options you can enable it by setting this variable `fetch_db_hosts` to true:
        fetch_db_hosts:
             description: When set, the db nodes are also fetched.
