### ISSUE TITLE
Add security rule to existing security list

### ISSUE THREAD

**Issue by rimagil** [oracle/oci-ansible-modules#124]
Is there module available to add security ingress/egress rule to an exist security list which has rules in it?

**Comment by mross22** [comment]
See oci_security_list: https://github.com/oracle/oci-ansible-modules/blob/master/library/oci_security_list.py#L174

If you specify `purge_security_rules: false` for an update, it should add the newly specified rules to the existing list.  By default `purge_security_rules` is true which wipes out existing rules.

**Comment by rimagil** [comment]
Will give that a try. Thanks
