### ISSUE TITLE
oci_security_list module need support for populating the 'description' field of a security rule.

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-ansible-modules#125]
Enhancement Request:

oci_security_list module need support for populating the 'description' field of a security rule.

Using these modules we are unable to populate 'description', but this options Available in OCI Tenancy Web Interface.

**Comment by nalsaber** [comment]
@vburamdo We are adding all of the missing features and services to our new oci-ansible-collection repo. Just notice the breaking changes for security lists in the [migration guide](https://github.com/oracle/oci-ansible-collection/blob/master/MigrationGuide.md)
> Options to purge or delete items from lists on resources are no longer supported is oci_security_list.

You can check the new module here:
https://github.com/oracle/oci-ansible-collection/blob/master/plugins/modules/oci_network_security_list.py

**Comment by vburamdo** [comment]
@nalsaber Thank you for the update, will the new module 'oci_network_security_list' will have features/options to purge or deleting existing ingress/egress rules? as our automation required to delete ingress/egress rules when required.

**Comment by nalsaber** [comment]
The default behavior for these fields has always been purge_{resource_name} = True, which remains true for the new modules. But there is no longer an option to specify purge_{resource_name} = False and only append new entries to the list. Thus, if you want to update a list you will need to supply the entire list, if you supply a subset of items they will completely replace the existing list.

**Comment by manojmeda** [comment]
@vburamdo If you keep the display names unique in your tenancy, then you could also use the "name as identifier" feature that is added in the new collections to keep your playbooks declarative. You can use the same task to create and update your resource i.e add/remove a security rule in this case. Please check https://github.com/oracle/oci-ansible-collection/blob/master/UserGuide.md. Please check and let us know if you need more info.

**Comment by vburamdo** [comment]
@nalsaber @manojmeda  Thanks for the details. Most our automatons is being used by Endusers/Customers to update Security Rules to the Existing Security List, as they mayn't be able to supply the entire list, can you please include 'purge' and 'delete' features in new module 'oci_network_security_list' too?

**Comment by vburamdo** [comment]
@nalsaber @manojmeda  can you please provide answer for the below?

1. When this new code will be released?
2. What is the impact if we use legacy modules? will we get support for legacy modules?

**Comment by nalsaber** [comment]
@vburamdo Thanks for feedback. We are looking at both options you mentioned. Just to understand the use case clearly, can you please clarify why your end users can't pull the list, add/remove rules rules then update the entire list?

**Comment by vburamdo** [comment]
@nalsaber They mayn't know 'ansible' and they just create one standard data driven csv template for adding security rules which our automation read this template and add to existing security list.
Pull and adding to existing Security rules is overhead work and there are chances of missing / making mistakes etc..

**Comment by vburamdo** [comment]
@nalsaber Also can you please provide your inputs for the below?

    1. When this new code will be released?
    2/ What is the impact if we use legacy modules? will we get support for legacy modules?

**Comment by nalsaber** [comment]
@vburamdo We are trying to estimate the effort if we add the purge feature to the new modules. **Legacy modules will have bug fixing support**. We would like to focus on providing the missing features and services in the new modules. We are expecting some customers will continue to use the old modules with the new modules until they fully migrate.

**Comment by vburamdo** [comment]
@nalsaber Thanks for the update.

**Comment by nalsaber** [comment]
We will add the purge feature to the new modules in the coming release.

**Comment by vburamdo** [comment]
@nalsaber  thank you also please consider to add 'delete_security_rules = yes' in new modules.

**Comment by nalsaber** [comment]
@vburamdo  This feature to purge was released last month:
https://github.com/oracle/oci-ansible-collection/blob/master/plugins/modules/oci_network_security_list.py
