### ISSUE TITLE
installed the roles from ansible-galaxy but the script samples are only adapted

### ISSUE THREAD

**Issue by brokedba** [oracle/oci-ansible-modules#126]
## Issue Report

**Describe the issue**

I added the modules using ansible-galaxy install but all the scripts in the sample directory 
aren't adapted  for using the roles.
I tried the roles in simple add fact request but It fails when I add roles in the always free launch instance . Can someone give me some guidance in how to add the roles section on  the sample and setup files without having erros at when runing them ?
Thank you   

**Environment**

* OS version:
ubuntu 
* Ansible version:

``` ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/koss/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Apr 15 2020, 17:07:12) [GCC 5.4.0 20160609] ``` 

* OCI Python SDK version:

    insert output of `2.14.0` here

* OCI Ansible Modules version:

  oracle.oci_ansible_modules (v1.18.0)

**Comment by nalsaber** [comment]
@KoussHD We currently provide sample playbooks that should run without any changes. If you want to use it as a Role, you have to check Ansible documentation on how to rewrite playbooks as Roles.

**Comment by KoussHD** [comment]
@nalsaber I finally adapted the sample to use the role. The funny thing is that I have ran the playbook twice and I had a twin instance created (see screenshot) and Idempotency was nowhere to be found (not so useful).
![image](https://user-images.githubusercontent.com/29458929/82963228-46ca6e00-9f90-11ea-922a-c2dbafb25a75.png)

By the way if it's old that means that Oracle didn't update  the role present in Ansible-Galaxy I thought Oracle kept some consistency  between github and galaxy.
I don't think anybody would risk using these modules in a prod tenancy.
cheers

**Comment by nalsaber** [comment]
Currently Galaxy has version 1.18.0. You are using 1.6.0 
https://galaxy.ansible.com/oracle/oci_ansible_modules

We have many customers using these modules in production tenancy. Idempotency does work for compute instances. I can help you if you share the playbooks. It is possible that you created a new network for each run that's why Idempotency didn't run. We have tests that cover Idempotency for all modules:
`
    ## Create/Launch
    - name: Create new compute instance
      oci_instance:
        name: "{{test_instance_name}}"
        shape: "{{test_instance_shape}}"
        compartment_id: "{{test_compartment_ocid}}"
        availability_domain: "{{test_availability_domain}}"
        metadata:
            foo: bar
            baz: quux
        source_details:
          source_type: "image"
          image_id: "{{image_ocid}}"
        vnic:
            hostname_label: "{{test_instance_name}}"
            subnet_id: "{{test_subnet_ocid}}"
            nsg_ids:
              - "{{ my_nsg_id }}"
        freeform_tags: "{ '{{ my_freeform_test_tag_key }}':'{{ my_freeform_test_tag_value }}' }"
        defined_tags: "{ '{{ test_tag_namespace_name }}':{'{{ test_tag_name }}':'{{test_instance_name}}-tag-value'} }"
      register: result
    # name: Set variable to current instance id
    - set_fact:
        my_instance_ocid: "{{result.instance.id}}"
    - debug:
        msg: "{{ result }}"
    - name: Assert that changed is true
      assert:
        that:
          - result.changed == True

    - name: Create new compute instance - idempotence test
      oci_instance:
        name: "{{test_instance_name}}"
        shape: "{{test_instance_shape}}"
        compartment_id: "{{test_compartment_ocid}}"
        availability_domain: "{{test_availability_domain}}"
        metadata:
            foo: bar
            baz: quux
        source_details:
          source_type: "image"
          image_id: "{{image_ocid}}"
        vnic:
            hostname_label: "{{test_instance_name}}"
            subnet_id: "{{test_subnet_ocid}}"
            nsg_ids:
              - "{{ my_nsg_id }}"
        freeform_tags: "{ '{{ my_freeform_test_tag_key }}':'{{ my_freeform_test_tag_value }}' }"
        defined_tags: "{ '{{ test_tag_namespace_name }}':{'{{ test_tag_name }}':'{{test_instance_name}}-tag-value'} }"
      register: result
    - debug:
        msg: "{{ result }}"
    - name: Assert that changed is False, and the older instance id is returned
      assert:
        that:
          - result.changed == False
`

**Comment by KoussHD** [comment]
Ok let me have a look . I must say it's very fresh as I did it last sunday.
here is my repo where you can find my playbook (sample and setup ) for an always free instance launch. https://github.com/KoussHD/ansible-examples/tree/master/oci-ansible/launch_free_instance
Feel free to check it out.  as for the version I did run 
>  $ ansible-galaxy install oracle.oci_ansible_modules

not sure why  the version was old

**Comment by KoussHD** [comment]
By the way I tried with assert and I am not sure I understand the logic . did you mean you need to run the first time with assert to true then all subsequent runs with assert=false ?

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
