### ISSUE TITLE
Support for the range parameter in the oci python module

### ISSUE THREAD

**Issue by poodge** [oracle/oci-ansible-modules#128]
## Issue Report

**Describe the issue**

Support for the range parameter in the oci python module 

**Expected behavior**

In the playbook you can use range to download chunks of the object 

**Environment**

* OS version: Oracle Linux Server release 7.6

* Ansible version: ansible 2.9.9

* OCI Python SDK version:  2.15.0

* OCI Ansible Modules version: 1.6.0-dev

**Ansible playbook to reproduce the issue**
- name: Download file
  oci_object:
    namespace: someNamespace
    bucket: someBucket
    object: someObject
    dest: someDir/someFile
    range: 0-21474836480

**Comment by AmeyaLokre** [comment]
Hello @poodge , we do not have support for the `range` option in oci-ansible-module. 
But this `range` option is supported in our new collection https://github.com/oracle/oci-ansible-collection in the `oci_object_storage_object_facts` module.
