### ISSUE TITLE
Enable oci_inventory.py to filter by tags (freeform and defined)

### ISSUE THREAD

**Issue by dmitrypol** [oracle/oci-ansible-modules#13]
## Issue Report

It would be nice to use dynamic inventory to filter by tags (just like we can by compartment)
```
oci_inventory.py --tags web ...
```
This way we can use `hosts: web` setting in playbook to run on instances tagged `web`.  

Also set the tags filter in other places like `oci_inventory.ini`.  I know that tags currently get returned and are stored in `ansible-oci.cache`

* Ansible version:
2.7.2

* OCI Python SDK version:
2.1.1

* OCI Ansible Modules version:
1.3.0

**Comment by rohitChaware** [comment]
Thanks @dmitrypol for raising this feature request. 

Are you only looking for a way so that a playbook can be run on specific tagged instances?

With the current implementation too, we can run the playbook tasks only on specific instances, say on instances having freeform tag `type=web`, by setting `hosts: tag_type=web`.

For example, with the following playbook `sample.yml`:
```
- name : Run command on each host tagged with type as web
  hosts: tag_type=web
  remote_user: opc
  tasks:
    - command: uname -a
      register: result
    - debug:
        msg: "{{ result }}"
```
execute `ansible-playbook -i contrib/inventory/oci_inventory.py sample.yml`.

Also, having an option to get only specific tagged instances will reduce the inventory creation time.

**Comment by dmitrypol** [comment]
the use case I am envisioning (based on how I managed infrastructure at previous jobs) is I could have compartment `app1` and `app2`.  In both compartments I would have servers tagged `web` where I would need to install Nginx.  Thank you for suggestion on using `tag_type`, this would accomplish my immediate need.  

I see the value of building dynamic inventory once and them using the `tag_type` filter in playbooks.  How would this approach scale if we have thousands of instances in spread across compartments?

**Comment by rohitChaware** [comment]
Yes, for such cases we need the ability to filter, filter by tag value, so that building inventory is scalable. 

We will address this feature to create inventory with filter options.

**Comment by dmitrypol** [comment]
I also figured out that you can use multiple tags in the filter like this `  hosts: tag_app_name=app1, tag_server_role=worker, tag_environment=prod` in playbooks.

**Comment by rohitChaware** [comment]
@dmitrypol Yes, it is possible. To run a playbook on hosts that match all tags, use:
```
hosts: tag_app_name=app1:tag_server_role=worker:&tag_env=prod
```

To learn more about using patterns to choose hosts in Ansible, refer: https://docs.ansible.com/ansible/2.7/user_guide/intro_patterns.html

**Comment by rohitChaware** [comment]
There is one more way to run a playbook on a selected group of hosts: using the `--limit` option. For example, with the following playbook `sample.yml`:

```
- name : Run command on all hosts
  hosts: all
  remote_user: opc
  tasks:
    - command: uname -a
      register: result
    - debug:
        msg: "{{ result }}"
``` 
execute 
`ansible-playbook -i contrib/inventory/oci_inventory.py sample.yml --limit "tag_app_name=app1:&tag_server_role=worker:&tag_env=prod"` 
to run the playbook only on hosts tagged with all the freeform tags: `app_name:app1`, `server_role:worker`, `env:prod`.

**Comment by dmitrypol** [comment]
thank you
