### ISSUE TITLE
oci_bucket module is unable to delete a bucket with its all objects

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-ansible-modules#130]
## Issue Report

oci_bucket module is unable to delete a bucket which has objects and pre-authenticated request at the bucket level when force=yes defined.

**Expected behavior**
It should be able to delete bucket along with it's all buckets when force=yes defined.

**Environment**

* OS version:
Red Hat Enterprise Linux Server release 7.8

* Ansible version:
ansible 2.9.9
  config file = /home/xxxx/xxxx/ansible.cfg
  configured module search path = [u'/root/.ansible/roles/oracle.oci_ansible_modules/library', u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python2.7/site-packages/ansible
  executable location = /root/bin/ansible
  python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]

* OCI Python SDK version:

    2.14.3

* OCI Ansible Modules version:

   1.6.0-dev

**Ansible playbook to reproduce the issue**

 - name: 'Deleting the bucket with all objects'
  delegate_to: localhost
  when: >
    bucket_ocid is defined
  oci_bucket:
     namespace_name: '{{ namespace_name }}'
     name: '{{ bucket_name }}'
     force: 'yes'
     state: 'absent'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'

**Comment by vburamdo** [comment]
Recieved following error when tried to delete bucket and with its objects.

TASK [oci_decomm_objectstorage : Deleting the bucket with all objects] ************************************************************************************************************************************************
task path: /home/xxxx/xxxx/roles/oci_decomm_objectstorage/tasks/main.yml:61
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1596727728.77-9846-102356616762872 && echo ansible-tmp-1596727728.77-9846-102356616762872="` echo /root/.ansible/tmp/ansible-tmp-1596727728.77-9846-102356616762872 `" ) && sleep 0'
Using module file /root/.ansible/roles/oracle.oci_ansible_modules/library/oci_bucket.py
<localhost> PUT /root/.ansible/tmp/ansible-local-31100bm3jDx/tmpRNo9mO TO /root/.ansible/tmp/ansible-tmp-1596727728.77-9846-102356616762872/AnsiballZ_oci_bucket.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1596727728.77-9846-102356616762872/ /root/.ansible/tmp/ansible-tmp-1596727728.77-9846-102356616762872/AnsiballZ_oci_bucket.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1596727728.77-9846-102356616762872/AnsiballZ_oci_bucket.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1596727728.77-9846-102356616762872/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_oci_bucket_payload_ePzj8Z/ansible_oci_bucket_payload.zip/ansible/modules/oci_bucket.py", line 258, in delete_bucket
  File "/tmp/ansible_oci_bucket_payload_ePzj8Z/ansible_oci_bucket_payload.zip/ansible/modules/oci_bucket.py", line 295, in delete_all_objects_in_bucket
  File "/root/.local/lib/python2.7/site-packages/oci/object_storage/object_storage_client.py", line 1113, in delete_object
    header_params=header_params)
  File "/root/.local/lib/python2.7/site-packages/oci/base_client.py", line 240, in call_api
    response = self.request(request)
  File "/root/.local/lib/python2.7/site-packages/oci/base_client.py", line 363, in request
    self.raise_service_error(request, response)
  File "/root/.local/lib/python2.7/site-packages/oci/base_client.py", line 533, in raise_service_error
    original_request=request)
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_user": null,
            "api_user_fingerprint": null,
            "api_user_key_file": null,
            "api_user_key_pass_phrase": null,
            "auth_type": "api_key",
            "compartment_id": null,
            "config_file_location": "/home/xxxxx/.oci/config",
            "config_profile_name": "xxxx_phx",
            "defined_tags": null,
            "force": true,
            "freeform_tags": null,
            "kms_key_id": null,
            "metadata": {},
            "name": "xxxx_xxx",
            "namespace_name": "xxxxxx",
            "public_access_type": "NoPublicAccess",
            "region": null,
            "state": "absent",
            "storage_tier": "Standard",
            "tenancy": null
        }
    },
    "msg": "the service is currently unavailable"
}
PLAY RECAP ************************************************************************************************************************************************************************************************************
localhost                  : ok=19   changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by nalsaber** [comment]
Can you please check if the new modules handle the force delete correctly?
https://github.com/oracle/oci-ansible-collection

**Comment by vburamdo** [comment]
@nalsaber In the new module 'oci_object_storage_bucket' force option not there.

**Comment by vburamdo** [comment]
also i tried with the following task.. still getting error while deleting objects.

- name: 'Fetch details of objects on {{ bucket_name }}'
  collections:
     - oracle.oci
  when: >
    namespace_name is defined and
    namespace_name|length > 0 and
    bucket_name is defined and
    bucket_name|length > 0
  delegate_to: localhost
  oci_object_storage_object_facts:
     namespace_name: '{{ namespace_name }}'
     bucket_name: '{{ bucket_name }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: object_results

- name: 'Deleting all objects on {{ bucket_name }}'
  collections:
     - oracle.oci
  delegate_to: localhost
  when: >
    object_results is defined
  oci_object_storage_object:
    namespace_name: '{{ namespace_name }}'
    bucket_name: '{{ bucket_name }}'
    object_name: "{{ item.name }}"
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    state: absent
  loop: '{{ object_results.objects }}'
  loop_control:
      label: '{{ item.name }}'


Error:

The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1597048006.92-15414-118341245831012/AnsiballZ_oci_object_storage_object.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1597048006.92-15414-118341245831012/AnsiballZ_oci_object_storage_object.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1597048006.92-15414-118341245831012/AnsiballZ_oci_object_storage_object.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.oracle.oci.plugins.modules.oci_object_storage_object', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py", line 407, in <module>
  File "/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py", line 399, in main
  File "/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_object_storage_custom_helpers.py", line 316, in delete
  File "/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_resource_utils.py", line 894, in delete
  File "/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py", line 344, in delete_resource
  File "/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_wait_utils.py", line 724, in call_and_wait
  File "/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py", line 131, in call_with_backoff
  File "/usr/lib/python2.7/site-packages/oci/object_storage/object_storage_client.py", line 825, in delete_object
    "delete_object got unknown kwargs: {!r}".format(extra_kwargs))
ValueError: delete_object got unknown kwargs: ['version_id']
failed: [localhost -> localhost] (item=xxxxxx-5033_test_results.txt) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "etag": null,
        "md5": null,
        "name": "xxxxxx-5033_test_results.txt",
        "size": null,
        "time_created": null
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1597048006.92-15414-118341245831012/AnsiballZ_oci_object_storage_object.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1597048006.92-15414-118341245831012/AnsiballZ_oci_object_storage_object.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1597048006.92-15414-118341245831012/AnsiballZ_oci_object_storage_object.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.oracle.oci.plugins.modules.oci_object_storage_object', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py\", line 407, in <module>\n  File \"/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py\", line 399, in main\n  File \"/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_object_storage_custom_helpers.py\", line 316, in delete\n  File \"/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_resource_utils.py\", line 894, in delete\n  File \"/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py\", line 344, in delete_resource\n  File \"/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_wait_utils.py\", line 724, in call_and_wait\n  File \"/tmp/ansible_oci_object_storage_object_payload_DEDSC3/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py\", line 131, in call_with_backoff\n  File \"/usr/lib/python2.7/site-packages/oci/object_storage/object_storage_client.py\", line 825, in delete_object\n    \"delete_object got unknown kwargs: {!r}\".format(extra_kwargs))\nValueError: delete_object got unknown kwargs: ['version_id']\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by manojmeda** [comment]
@vburamdo From the error message it looks like you are using an older version of `oci` package which didn't support some of the module parameters. It is recommended to use latest version of `oci` package when using collections modules. Can you please try with the latest version and let us know if you still see the error.

PS: The oci package is being picked up from this location (/usr/lib/python2.7/site-packages/oci). Is this the intended one?

**Comment by vburamdo** [comment]
@manojmeda  thank you, after upgrading to new `oci` package it worked. Also are there any plans to include '`force`' option for the module '`oci_object_storage_bucket`'? like we had for `oci_bucket`.

**Comment by vburamdo** [comment]
@manojmeda also please advice how list and delete `Pre-Authenticated Requests`

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
