### ISSUE TITLE
how to launch instance with vnic type 'PARAVIRTUALIZED' using oci_compute_instance? 

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-ansible-modules#133]
[oci_linux_windows.txt](https://github.com/oracle/oci-ansible-modules/files/5288242/oci_linux_windows.txt)
## Issue Report

**Describe the issue**
We would like to launch instance with it's 'vnic' type 'PARAVIRTUALIZED', using oci_compute_instance module how to achieve this?

A clear and concise description of what the issue is.

**Expected behavior**

**Environment**

* OS version: Red Hat Enterprise Linux Server release 7.8 (Maipo)

* Ansible version:

ansible 2.9.9
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python2.7/site-packages/ansible
  executable location = /root/bin/ansible
  python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]

* OCI Python SDK version:

2.21.5

* OCI Ansible Modules version:

   1.18.0

**Ansible playbook to reproduce the issue**

[oci_linux_windows.txt](https://github.com/oracle/oci-ansible-modules/files/5288249/oci_linux_windows.txt)

**Comment by vburamdo** [comment]
`
- name: 'OCI Instance - Creating Instance ( Linux / Windows ).'
  collections:
    - 'oracle.oci'
  delegate_to: 'localhost'
  oci_compute_instance:
    agent_config:
      is_management_disabled: 'False'
      is_monitoring_disabled: 'False'
    availability_domain: '{{ oci_ad_name }}'
    compartment_id: '{{ oci_compartment_ocid }}'
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    create_vnic_details:
      assign_public_ip: '{{ assign_public_ip | default("True") }}'
      display_name: '{{ inventory_hostname }}'
      hostname_label: '{{ oci_instance_hostname }}'
      nsg_ids: '{% if oci_attach_to_nsg is defined and oci_attach_to_nsg and oci_nsg_ocids is defined and oci_nsg_ocids is iterable %}{{ oci_nsg_ocids }}{% else %}{{ omit }}{% endif %}'
      skip_source_dest_check: 'No'
      subnet_id: '{{ oci_vcn_subnet_ocid }}'
    display_name: '{{ inventory_hostname }}'
    fault_domain: '{% if oci_faultdomain is defined %}{{ oci_faultdomain }}{% else %}{{ omit }}{% endif %}'
    force_create: 'No'
    key_by: 'display_name'
    metadata: '{{ instance_metadata | default(omit) }}'
    shape: '{{ oci_shape }}'
    shape_config: '{{ shape_config | default(omit) }}'
    launch_options:
       network_type: "PARAVIRTUALIZED"
    source_details:
      image_id: '{{ oci_image_ocid }}'
      source_type: 'image'
    state: 'present'
    wait: 'Yes'
    wait_timeout: '1800'
  register: 'create_instance_result'
`

**Comment by vburamdo** [comment]
oci_compute_instance:
    display_name: myinstance1
    availability_domain: Uocm:PHX-AD-1
    compartment_id: ocid1.compartment.oc1..xxxxxEXAMPLExxxxx...vm62xq
    shape: VM.Standard2.1
    .
    .
    launch_options:
       network_type: "PARAVIRTUALIZED"

**Comment by vburamdo** [comment]
{code}
  oci_compute_instance:
    display_name: myinstance1
    availability_domain: Uocm:PHX-AD-1
    compartment_id: ocid1.compartment.oc1..xxxxxEXAMPLExxxxx...vm62xq
    shape: VM.Standard2.1
    .
    .
    launch_options:
       network_type: "PARAVIRTUALIZED"
{code}

**Comment by vburamdo** [comment]
`
[oci_linux_windows.txt](https://github.com/oracle/oci-ansible-modules/files/5288246/oci_linux_windows.txt)
`

**Comment by vburamdo** [comment]
Error:

FAILED! => \{"changed": false, "msg": "Unsupported parameters for (oci_compute_instance) module: launch_options Supported parameters include: agent_config, api_user, api_user_fingerprint, api_user_key_file, api_user_key_pass_phrase, auth_type, availability_domain, compartment_id, config_file_location, config_profile_name, create_vnic_details, dedicated_vm_host_id, defined_tags, display_name, extended_metadata, fault_domain, force_create, freeform_tags, hostname_label, image_id, instance_id, ipxe_script, is_pv_encryption_in_transit_enabled, key_by, metadata, preserve_boot_volume, region, shape, shape_config, source_details, state, subnet_id, tenancy, wait, wait_timeout"}

**Comment by manojmeda** [comment]
@vburamdo Which version of oci ansible collection are you using? This option (`launch_options`) was added in the version 2.5.0. Can you please try with that or a later version and check.

**Comment by vburamdo** [comment]
@manojmeda Thanks, i have installed newer version and able to launch instance with 'launch_options'.
