### ISSUE TITLE
Ansible api for http redirect from http to https in LBAAS missing

### ISSUE THREAD

**Issue by varrajan** [oracle/oci-ansible-modules#134]
## Issue Report

**Describe the issue**
Hello LBAAS experts,

I have a customer trying to automate the LBAAS provisioning process. Ansible api for http redirect from http to https in LBAAS is missing. We reviewed the documentation and the api's but couldnt find it.. 

Thanks, 
Varun

A clear and concise description of what the issue is.

**Expected behavior**

**Environment**

* OS version:

* Ansible version:

    insert output of `ansible --version` here

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here

* OCI Ansible Modules version:

    insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by nalsaber** [comment]
Did you check if the feature is present in the new modules?
https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/index.html
https://github.com/oracle/oci-ansible-collection

We are not supporting any new features in the legacy modules (oci-ansible-modules)

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
