### ISSUE TITLE
Creation of compute in PHX failes with "Max retries exceeded with url"

### ISSUE THREAD

**Issue by zdudic** [oracle/oci-ansible-modules#136]
## Issue Report

**Describe the issue**

This is simple playbook to create compute, only one module "oci_instance". It works well in IAD, but fails in PHX. 

**Expected behavior**

I expect OCI PHX compute to be created. It works as expected in IAD, the IAD compute is created very well.  

**Environment**
Python virtual env is "oci-2.2.3"

* OS version:
OL7
* Ansible version:

   ansible 2.7.9
  config file = None
  configured module search path = [u'/home/zdudic/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /workspace/zdudic/python-virtualenv/oci-2.2.3/lib/python2.7/site-packages/ansible
  executable location = /workspace/zdudic/python-virtualenv/oci-2.2.3/bin/ansible
  python version = 2.7.5 (default, May 27 2020, 06:51:48) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.1)]

* OCI Python SDK version:

   2.2.3

* OCI Ansible Modules version:

  1.19.0
**Ansible playbook to reproduce the issue**

    This playbook for PHX fails, please use your own variables. Equivalent playbook for IAD works well. 

---
- name : Provision OCI Compute 
  connection: local
  hosts: localhost
  vars_files: vars.yml   # please use your variables !!!
  tasks:
       - name: Create phx compute
         oci_instance:
            config_profile_name: 'PHOENIX'  # default is DEFAULT
            name: "{{ item }}"
            availability_domain: "{{ availability_domain_phx }}"
            compartment_id: "{{ compartment_id }}"
            source_details:
               source_type: image           
               image_id: "{{ image_id }}"
            preserve_boot_volume: no   # remove boot volume when compute is terminated
            shape: "{{ shape }}"
            vnic:
                 subnet_id: "{{ subnet_id }}"   
          with_items:   
            - some-phx-name

Errors are:

failed: [localhost] (item=some-phx-name) => {
    "changed": false,
    "item": "svn16ol6ociphx",
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/zdudic/.ansible/tmp/ansible-tmp-1607379268.83-106497996453065/AnsiballZ_oci_instanc  _ansiballz_main()\n  File \"/home/zdudic/.ansible/tmp/ansible-tmp-1607379268.83-106497996453065/AnsiballZ_oci_instance.py\", line 105, in _ansiballz_main\mp_path, ANSIBALLZ_PARAMS)\n  File \"/home/zdudic/.ansible/tmp/ansible-tmp-1607379268.83-106497996453065/AnsiballZ_oci_instance.py\", line 48, in invoke_mod_', mod, module, MOD_DESC)\n  File \"/tmp/ansible_oci_instance_payload_11zakS/__main__.py\", line 1513, in <module>\n  File \"/tmp/ansible_oci_instance_payl94, in main\n  File \"/tmp/ansible_oci_instance_payload_11zakS/__main__.py\", line 1353, in create_one_instance\n  File \"/tmp/ansible_oci_instance_payload_ad.zip/ansible/module_utils/oracle/oci_utils.py\", line 577, in check_and_create_resource\n  File \"/tmp/ansible_oci_instance_payload_11zakS/ansible_oci_insutils/oracle/oci_utils.py\", line 199, in list_all_resources\n  File \"/workspace/zdudic/python-virtualenv/oci-2.2.3/lib/python2.7/site-packages/oci/paginat03, in list_call_get_all_results\n    for response in list_call_get_all_results_generator(list_func_ref, 'response', *list_func_args, **list_func_kwargs):\n-virtualenv/oci-2.2.3/lib/python2.7/site-packages/oci/pagination/pagination_utils.py\", line 271, in list_call_get_all_results_generator\n    call_result = _retrying_call(list_func_ref, *list_func_args, **list_func_kwargs)\n  File \"/workspace/zdudic/python-virtualenv/oci-2.2.3/lib/python2.7/site-packages/oci/re_retrying_call\n    return func_ref(*func_args, **func_kwargs)\n  File \"/workspace/zdudic/python-virtualenv/oci-2.2.3/lib/python2.7/site-packages/oci/corein list_instances\n    response_type=\"list[Instance]\")\n  File \"/workspace/zdudic/python-virtualenv/oci-2.2.3/lib/python2.7/site-packages/oci/base_client response = self.request(request)\n  File \"/workspace/zdudic/python-virtualenv/oci-2.2.3/lib/python2.7/site-packages/oci/base_client.py\", line 336, in reqtException(e)\noci.exceptions.RequestException: HTTPSConnectionPool(host='iaas.us-phx-1.oraclecloud.com', port=443): Max retries exceeded with url: /2016091compartment.oc1..aaaaaaaahob5f2d6sqf6znwcc3hpkrroa75tteahhvzisetd3pcjxuiyrrwa&sortBy=TIMECREATED (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL rtificate', 'certificate verify failed')],)\",),))\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by manojmeda** [comment]
@zdudic Sorry for the delay in response. From the logs, I see that you are using `us-phx-1` as region. It should be `us-phoenix-1`.

Note: These modules are currently in maintenance mode and would be deprecated soon in favour of the new collection modules. PFB the links which can help you get started with the new collection:

OCI Ansible Collection: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/ansible.htm
Github: https://github.com/oracle/oci-ansible-collection
Module Index: https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/index.html
Migration guide: https://github.com/oracle/oci-ansible-collection/blob/master/MigrationGuide.md

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
