### ISSUE TITLE
ERROR! couldn't resolve module/action 'oci_internet_gateway'. This often indicates a misspelling, missing collection, or incorrect module path.

### ISSUE THREAD

**Issue by psaini79** [oracle/oci-ansible-modules#138]
## Issue Report

**Describe the issue**
Using ansible OCI modules to create the VCN and kept on failing with the error mentioned in the title of this thread.*

ERROR! couldn't resolve module/action 'oci_internet_gateway'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/OCI_ANSIBLE_DIR1/oracle-sharding-si-k8s/oracle-sharding-si-k8s-master/oracle-sharding-si-ansible-playbooks/roles/oci-setup-oke-network/tasks/main.yml': line 18, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name:  Create and internet gateway
  ^ here

**Expected behavior**

The creation of a VCN should go fine. It used to work previously.

**Environment**

* OS version: Oracle Linux Server release 7.9

* Ansible version:

  `ansible 2.10.5` 

* OCI Python SDK version:

`2.8.0` 

* OCI Ansible Modules version:

   `1.19.0` 

**Ansible playbook to reproduce the issue**

   To reproduce the issue, you need to follow the repo give below:
https://github.com/oracle/db-sharding/tree/master/oke-based-sharding-deployment

**Comment by manojmeda** [comment]
@psaini79 These modules are currently in maintenance mode and would be deprecated soon. I see that you are using ansible 2.10. Currently the installation script only works for ansible <= 2.9. I would strongly recommend you to move to the new oci ansible collection. PFB the links which can help you get started with the new collection:

OCI Ansible Collection: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/ansible.htm
Github: https://github.com/oracle/oci-ansible-collection
Module Index: https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/index.html
Migration guide: https://github.com/oracle/oci-ansible-collection/blob/master/MigrationGuide.md

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
