### ISSUE TITLE
Mail module not worked remote windows server

### ISSUE THREAD

**Issue by Arun765** [oracle/oci-ansible-modules#141]
## Issue Report

**Describe the issue**

We have used mail module to send an mail from an remote windows server.

**Expected behavior**

We have received an below error,
fatal: [150.136.172.28]: UNREACHABLE! => {"changed": false, "msg": "ssl: the specified credentials were rejected by the server", "unreachable": true}

**Environment**

* OS version:

We are running the code from oracle linux 7.7

* Ansible version:

ansible 2.9.10

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here
2.26.0
* OCI Ansible Modules version:

    insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here
1.6.0-dev
**Ansible playbook to reproduce the issue**
Used below code for ansible mail module,
(oci-ansible-getting-started) [root@syntaxatm01 ~]# cat mailwindows2.yml
---
 - name: Mail
   hosts: windows
   tasks:
     - name: Send Mail
       community.general.mail:
          host: "smtp-mail.outlook.com"
          username: "arcbss@xxx.com"
          port: 587
          from: "arcbss@xxx.com"
          password: "arcbsxxxcom"
          to: "arcbss@xxx.com"
          subject: "ansible"
          body: "Security patches has been applied on server{{ ansible_hostname }}"
          secure: starttls
Please help me to resolve this issue.
    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by manojmeda** [comment]
@Arun765 The `community.general.mail` is developed by the community and not our team. Please reach out to the team that developed this module.

**Comment by Arun765** [comment]
@manojmeda Is there any module available for sending mail from remote windows server.

**Comment by manojmeda** [comment]
@Arun765 Our modules are mainly focused on the infrastructure automation on OCI. There may be some third party module but I am not aware of a specific module you can use for this scenario. I would recommend you to search in the community collection. Closing this ticket since this scenario is not related to OCI Ansible.
