### ISSUE TITLE
Ansible OCI Create Windows instance

### ISSUE THREAD

**Issue by Arun765** [oracle/oci-ansible-modules#142]
## Issue Report

**Describe the issue**

We are trying to create windows instance, but receives below error.

failed: [localhost] (item={u'Shape': u'VM.Standard.E4.Flex', u'Subnet_name': u'ProdAD1', u'AD': u'OYHW:US-ASHBURN-AD-1', u'FD': u'FAULT-DOMAIN-3', u'Image_OCID': u'ocid1.image.oc1.iad.aaaaaaaan6wdens6qkfrjbk4x6r763u6lkayjx6kvmfmufkducxd3ruqlrkq', u'Name': u'ENTPD01'}) => {"InstancesJDEP": {"AD": "OYHW:US-ASHBURN-AD-1", "FD": "FAULT-DOMAIN-3", "Image_OCID": "ocid1.image.oc1.iad.aaaaaaaan6wdens6qkfrjbk4x6r763u6lkayjx6kvmfmufkducxd3ruqlrkq", "Name": "ENTPD01", "Shape": "VM.Standard.E4.Flex", "Subnet_name": "ProdAD1"}, "ansible_loop_var": "InstancesJDEP", "changed": false, "msg": "Invalid ShapeConfig: null (Cannot launch flexible instance without ShapeConfig)"}

**Expected behavior**

**Environment**

* OS version:

* Ansible version:

    insert output of `ansible --version` here
ansible 2.9.13

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here
2.21.4
* OCI Ansible Modules version:

    insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here
1.19.0
**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)
---
- name: User
  connection: local
  hosts: localhost
  tasks:
    - read_csv:
          path: /root/OCI_New_Customer_Info_V1/InstancesJDEP.csv
      register: InstanceJDEP

    - name: Gather Details of subnet
      oracle.oci.oci_network_subnet_facts:
         compartment_id: "{{ lookup('env', 'SAMPLE_TENANCY_OCID') }}"
         display_name: "{{ InstancesJDEP.Subnet_name }}"

      loop: "{{ InstanceJDEP.list }}"
      loop_control:
          loop_var: InstancesJDEP

      register: result
    - debug: msg="{{ result }}"

    - name: Launch/create an instance
      oracle.oci.oci_compute_instance:
          name: "{{ InstancesJDEP.Name }}"
          availability_domain: "{{ InstancesJDEP.AD }}"
          fault_domain: "{{ InstancesJDEP.FD }}"
          compartment_id: "{{ lookup('env', 'SAMPLE_JDEPCOMP_OCID') }}"
          shape: "{{ InstancesJDEP.Shape }}"
          metadata:
             ssh_authorized_keys: "{{ lookup('file', '/root/Ansible/Excelvar/pub.pem' ) }}"
          source_details:
             source_type: image
             image_id: "{{ InstancesJDEP.Image_OCID }}"
          create_vnic_details:
             subnet_id: "{{ result.results[0].subnets[0].id }}"

      loop: "{{ InstanceJDEP.list }}"
      loop_control:
          loop_var: InstancesJDEP

Below is the variable file,

ENTPD01,OYHW:US-ASHBURN-AD-1,FAULT-DOMAIN-3,VM.Standard.E4.Flex,ProdAD1,ocid1.image.oc1.iad.aaaaaaaar4qrcgzyigsnpgy3c7fx53r7hft6l5gowslkxnmxauzexjctysra

**Comment by manojmeda** [comment]
@Arun765 I see that you are using the new OCI Ansible collection. Please create any issues related to OCI Ansible collection in the github repository (https://github.com/oracle/oci-ansible-collection) in the future.

The error is not specific to the OCI ansible module. It is a service error and I think the error (`Cannot launch flexible instance without ShapeConfig`) is self explanatory. You need to pass the `shape_config` parameter for flexible shapes. Please refer to the module documentation https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_compute_instance_module.html#parameters and OCI shapes documentation https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm for more details.

**Comment by Arun765** [comment]
After Adding shape_config parameter, we have successfully created windows instance.
