### ISSUE TITLE
ImportError: No module named oci

### ISSUE THREAD

**Issue by zdudic** [oracle/oci-ansible-modules#15]
The command "ansible-playbook -vvv <some-file.yml>"  finish with the error:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_VKF3k9/ansible_module_oci_image_facts.py", line 129, in <module>
    from ansible.module_utils.oracle import oci_utils
  File "/tmp/ansible_VKF3k9/ansible_modlib.zip/ansible/module_utils/oracle/oci_utils.py", line 14, in <module>
ImportError: No module named oci

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_VKF3k9/ansible_module_oci_image_facts.py\", line 129, in <module>\n    from ansible.module_utils.oracle import oci_utils\n  File \"/tmp/ansible_VKF3k9/ansible_modlib.zip/ansible/module_utils/oracle/oci_utils.py\", line 14, in <module>\nImportError: No module named oci\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

It's expected to complete with no errors. 

[1] oci and oci-ansible-modules are installed in its own virtual environment, named "oci"

(oci) [zdudic@ca-ansible oci] pip show oci
Name: oci
Version: 2.1.1
Summary: Oracle Cloud Infrastructure Python SDK
Home-page: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/index.html
Author: Oracle
Author-email: joe.levy@oracle.com
License: Universal Permissive License 1.0 or Apache License 2.0
Location: /python-virtualenv/oci/lib/python2.7/site-packages
Requires: cryptography, pyOpenSSL, configparser, pytz, python-dateutil, certifi
Required-by: oci-cli

[2] ansible version is : 

(oci) [zdudic@ca-ansible oci] ansible --version
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/zdudic/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /python-virtualenv/oci/lib/python2.7/site-packages/ansible
  executable location = /python-virtualenv/oci/bin/ansible
  python version = 2.7.5 (default, Jul  3 2018, 06:28:28) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)]

[3] "ansible python module location" from [2] should be okay, since modules are present in directory /python-virtualenv/oci/lib/python2.7/site-packages/ansible/modules/cloud/oracle

[4] OS is Oracle Linux Server release 7.5

 [5]    OCI Python SDK version:

    (oci) [zdudic@ca-ansible oci] python -c "import oci;print(oci.__version__)"
           2.1.1

[6]  OCI Ansible Modules version:

 (oci) [zdudic@ca-ansible oci] python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"
    1.3.0

[7]  Ansible playbook to reproduce the issue, here is simple playbook to list a tenancy.

>
---
- name : Tenancy playbook
  connection: local
  hosts: localhost
  tasks:
     - name: List details about LV tenancy
       oci_tenancy_facts:
          id: "ocid1.tenancy.oc1..aaaa...dygfq"
       register: result
     - name: Dump result
       debug:
          msg: '{{result}}'

>

**Comment by sivakumart** [comment]
@zdudic The playbook lokks good. It appears that somehow the OCI ansible modules are not able to find `oci` in the python path.

Could you perform the following and share your results? This can help us troubleshoot this further.

- Please share the entry for 'localhost' (if you have a hosts file /etc/ansible/hosts or a custom hosts file in /etc/ansible/ansible.cfg, ~/.ansible.cfg).
If you don't have one, does adding this in your hosts file help?
> [localhost]
> localhost ansible_connection=local ansible_python_interpreter=python

- It looks like you are using another 'ansible' installed in your system (yum installed EPEL based ansible). Could you please try also installing ansible in your virtual environment and using that instead

- Please share the output of `which ansible-playbook`, `which python`, `pip freeze|grep ansible`, `pip freeze|grep oci`.

Thanks.

**Comment by zdudic** [comment]
Thanks Sivakumar. 
I use ansible from virtual env, it's /python-virtualenv/oci/bin/python, not OS one which is /bin/python.  
You feedback about /etc/ansible/hosts  was valuable. Indeed it was localhost entry there, and after I removed it, seems all is good. I suspect this was incidentally added. 

If proposed lines are added:
[localhost]
localhost ansible_connection=local ansible_python_interpreter=python
... playbook still works, so I believe all is good now.

**Comment by sivakumart** [comment]
@zdudic: Glad to hear that it worked out for you and thanks for reporting your experience.
