### ISSUE TITLE
oci-ansible modules backward compatibility

### ISSUE THREAD

**Issue by shomikb** [oracle/oci-ansible-modules#21]
Are the oci modules backward compatable ? i have developed code using 1.4.0 . Now i see 1.5.0 is available. Should i have to change my code or is it backward compatable.

**Comment by sivakumart** [comment]
Thanks @shomikb for your question and using OCI ansible modules. Yes, OCI ansible modules are backwards compatible. When a new release breaks compatibility (we have not done this so far. We have only deprecated a few module options so far.) and would require a change in your playbooks, the new release's release notes (https://github.com/oracle/oci-ansible-modules/releases/) and changelog (https://github.com/oracle/oci-ansible-modules/blob/master/CHANGELOG.md) would clearly indicate the backward compatiblity issue and workarounds (if any). Thanks.
