### ISSUE TITLE
querying from Oracle images

### ISSUE THREAD

**Issue by shomikb** [oracle/oci-ansible-modules#22]
Hi ,
I am currently not able to query the Oracle Images and get the app catalog listings and app catalog subscriptions in OCI ansible modules. Siva said it will be available soon. So waiting for that. 
Regards,
Shomik Basu

**Comment by sivakumart** [comment]
Thanks @shomikb for raising this. Support for app catalog subscriptions and listings would be available in the upcoming release.

**Comment by manojmeda** [comment]
@shomikb This feature is added in the latest release (`v1.6.0`). Please check out the below modules we added:

- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_app_catalog_listing_facts_module.html#oci-app-catalog-listing-facts-module
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_app_catalog_listing_resource_version_facts_module.html#oci-app-catalog-listing-resource-version-facts-module
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_app_catalog_listing_agreement_module.html#oci-app-catalog-listing-agreement-module
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_app_catalog_subscription_module.html#oci-app-catalog-subscription-module
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_app_catalog_subscription_facts_module.html#oci-app-catalog-subscription-facts-module

Please try out the modules and share any feedback that you may have. Thanks.
