### ISSUE TITLE
Password for Windows instance

### ISSUE THREAD

**Issue by shomikb** [oracle/oci-ansible-modules#23]
Hi,
Currently after provisioning windows instance the oci generates a windows passowrd which i have to change manually. I was told there are some ways using terraform this can be done. But even putting the value in the userdata section of the advanced option, i am not able to do it.
Regards,
Shomik Basu

**Comment by sivakumart** [comment]
Thanks @shomikb for raising this. As we had discussed, fixing the userdata as discussed in https://github.com/terraform-providers/terraform-provider-oci/tree/master/docs/examples/compute/windows/userdata helped you to reset the initial windows password.

https://github.com/terraform-providers/terraform-provider-oci/tree/master/docs/examples/compute/windows shows how the initial password set for Windows compute instances can be reset using Cloudbase-init. Following the same technique also works with OCI ansible modules. Thanks. Closing this issue for now as this is resolved.
