### ISSUE TITLE
oci_volume errs when initializing from a volume backup of size greater than 50 GB

### ISSUE THREAD

**Issue by bellarmin** [oracle/oci-ansible-modules#24]
## Issue Report

I am trying to get the display name of the volumes attached to the instance. It is not providing the excat display_name rather than providing as "display_name": "volumeattachment20181220230832",

A clear and concise description of what the issue is.

I trying to detach the specific display named volumes from the instance trying to get the names from oci_volume_attachment_facts. 

Oracle Linux 7

* OS version:

* Ansible version:

  ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/opc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  1 2018, 03:12:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)]

* OCI Python SDK version:

2.1.3

* OCI Ansible Modules version:

1.5.0

**Ansible playbook to reproduce the issue**

       - name: Get volume attachment information for a specified compartment & instance
      oci_volume_attachment_facts:
        config_file_location: ''
        config_profile_name: ''
        compartment_id: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        instance_id: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
      register: result
    - name: Dump result
      debug:
        msg: '{{result}}'

**Comment by rohitChaware** [comment]
`oci_volume_attachment_facts` module retrieves information of volume attachments. The `display_name` returned by this module is the name of the volume attachment.

To get the name of the attached volume, we can use `oci_volume_attachment_facts` followed by `oci_volume_facts` with `id` option set to the value of `volume_id` returned by `oci_volume_attachment_facts`.

**Comment by rohitChaware** [comment]
@bellarmin For example, we can do it as in the playbook below:

```
- name: Get block volumes attached to an instance
  connection: local
  hosts: localhost
  tasks:
    - name: List volume attachments
      oci_volume_attachment_facts:
        instance_id: ocid1.instance.oc1.iad.xxxxx
        compartment_id: ocid1.compartment.oc1..xxxxx
      register: result
    - name: Get block volume facts
      oci_volume_facts:
        id: "{{ item.volume_id }}"
      with_items: "{{ result.volume_attachments }}"
      when: item.volume_id.find("bootvolume") == -1
      register: block_volumes
    - name: Print block volume names
      debug:
        msg: "{{ item[1].display_name }}"
      with_subelements:
        - "{{ block_volumes.results }}"
        - volumes
```

**Comment by bellarmin** [comment]
Thanks a lot Rohit. The actual requirement is i have a to detach a volumes which contains the string name as "asm" from the instance. The above example works well and it is printing all the volumes.
Could you please provide an example which can detach the volumes contains a name as "asm".

**Comment by rohitChaware** [comment]
Thanks for sharing the use case.

For this use case: attaching a volume to an instance and detaching it later, I would suggest using the `oci_volume_attachment` module(refer https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_volume_attachment_module.html#examples for examples) to attach the volume to the instance, register the returned result and then later, use the `id`(volume attachment OCID) from the registered result(`"{{ result.volume_attachment.id }}"`) to detach the volume.

**Comment by bellarmin** [comment]
Thanks Rohit. I am trying bit hard for the below requirement. 

Every we used to take a full volume backup of few asm luns using the volume group backup. Once the backup is ready we need to create a volume from that backup volumes and attach it to the new instance by removing the last week asm disks and attaching the currently created volumes from backup.

Some how i have cracked till removing the volumes from the instance and getting the volume ids of backup volumes. I am currently facing an issue while creating a volumes from the backup volumes.

Using the below playbook, and getting an error as "{'status': 400, 'message': u'Backup size 1048576 is greater than the requested volumeSize 51200. Could you please help on it.

---
- name : Playbook to mount a prod vol backup disk to sup environment
  connection: local
  hosts: localhost

  tasks:
    - name: Get information of a volume group backup
      oci_volume_group_backup_facts:
        config_file_location: ''
        config_profile_name: ''
        id: 'XXXXXXX'
      register: backup_vol
    - set_fact:
         vol_ids:
           asm-01: "{{backup_vol.volume_group_backups[0].volume_backup_ids[0]}}"
           asm-02: "{{backup_vol.volume_group_backups[0].volume_backup_ids[1]}}"
           asm-03: "{{backup_vol.volume_group_backups[0].volume_backup_ids[2]}}"

    - name: Create a volume and initialize it from a backup
      oci_volume:
        config_file_location: 'XXX'
        config_profile_name: 'XXX'
        availability_domain: lKQM:US-ASHBURN-AD-1
        compartment_id: 'XXXXX'
        name: "{{item.key}}"
        source_details:
          id: "{{item.value}}"
          type: volumeBackup
      with_dict:
        - "{{vol_ids}}"
      register: vol_created

**Comment by rohitChaware** [comment]
Thanks @bellarmin for using these modules for your interesting use case. The error

>  {'status': 400, 'message': u'Backup size 1048576 is greater than the requested volumeSize 51200}

is happening because `oci_volume` module has default value for `size_in_gbs` as 50 GB(51200 MB). If a volume is created using `source_details` option without specifying the `size_in_gbs` option and the source volume/volume backup has size more than 50 GB, we will get this error.

Till we fix this in the upcoming release, we can work around by avoiding using the default value for `size_in_gbs` in `oci_volume` module. In the playbook you shared, we can pass the size of a volume backup while creating a volume. Please refer the below playbook for reference:

```
- name: Get information of a volume group backup
  oci_volume_group_backup_facts:
    id: "{{ vol_grp_backup_ocid }}"
  register: result

- name: Get information of volume backups in the volume group backup
  oci_volume_backup_facts:
    id: "{{ item }}"
  register: volbackups
  with_items: "{{ result.volume_group_backups[0].volume_backup_ids }}"

- debug:
    msg: "{{ volbackups }}"

- name: Create block volumes restored from volume backups
  oci_volume:
    display_name: "asm-{{ indx }}"
    availability_domain: "{{ test_availability_domain }}"
    compartment_id: "{{test_compartment_ocid}}"
    size_in_gbs: "{{item[1].size_in_gbs}}"
    source_details:
      id: "{{item[1].id}}"
      type: "volumeBackup"
  register: result
  with_subelements:
    - "{{ volbackups.results }}"
    - volume_backups
  loop_control:
    index_var: indx

- debug:
    msg: "{{ result }}"

```

**Comment by bellarmin** [comment]
Thanks @rohitChaware for sharing the above reference. I will test it.

**Comment by bellarmin** [comment]
@rohitChaware tested and worked well. The volumes are getting created without any issue. I am struggling a bit a get those volumes attached to the instance. Not sure how to get those ids and assigned to it. 
I am able to set facts, hope it can be achievable without setting a facts based on above example. Tried lot, but no luck. Please share an example it could be a great helpful.

**Comment by bellarmin** [comment]
Finally achieved it,
    - name: Attach a volume to an instance
      oci_volume_attachment:
        config_file_location: '~/.oci/config'
        config_profile_name: '{{ profile }}'
        instance_id: "{{ instanceid }}"
        type: iscsi
        volume_id: "{{item.volume.id}}"
      register: vol_attach
      with_items:
        -  "{{ newvols.results }}"

**Comment by rohitChaware** [comment]
@bellarmin Great to know that you achieved the use case using oci-ansible-modules. Glad I could help. Thanks.

**Comment by rohitChaware** [comment]
@bellarmin A new release [1.6.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.6.0) of Oracle Cloud Infrastructure Ansible modules was posted today and it has fixed this issue.

Please try out the modules and share any feedback that you may have. Thanks.
