### ISSUE TITLE
Key error in inventory-script.py

### ISSUE THREAD

**Issue by gitnomnom** [oracle/oci-ansible-modules#25]
## Issue Report

When calling oci_inventory.py an error "KeyError: None" occurs and no inventory is returned.

**Expected behavior**

List of OCI inventory should be returned.

**Environment**

* OS version: Oracle Linux 7.5

* Ansible version:

ansible 2.7.6

* OCI Python SDK version:

2.1.7

* OCI Ansible Modules version:

1.5

**Ansible playbook to reproduce the issue**

Not relevant

* Underlying issue:
The function build_inventory_for_instance(..) calls self.get_region_from_short_name(instance.region) where instance.region is already the "long" version (e.g. eu-frankfurt-1) and then get_region_from_short_name returns None.

* Possible fixes: Checking in get_region_from_short_name if the region input matches either keys or values from the dict, not just the values. Or figuring out why the assumption is that the region is the short version.

Edit: Spelling

**Comment by manojmeda** [comment]
@gitnomnom We made that assumption because that the OCI SDK/API returns short names for ashburn and phoenix regions. Looks like it returns full names for other regions. Thanks for pointing this out. We will include the fix in the next release.

**Comment by manojmeda** [comment]
@gitnomnom This issue has been fixed in the latest release (`v1.6.0`). Could you please check and let us know if you face any issues.

**Comment by gitnomnom** [comment]
Yes, it works now. Thanks!
