### ISSUE TITLE
oci_instance terminate erroring

### ISSUE THREAD

**Issue by saswamy** [oracle/oci-ansible-modules#27]
## Issue Report
running simple oci_instance terminate and it keeps erroring 

**Describe the issue**
running simple oci_instance terminate and it keeps erroring with below : 

TASK [Terminate/delete an instance] ***********************************************************************************************
task path: /part1/work/cloud/ansible/ebs/ansible_cloudvm_layout/test_del_4.yml:13
Saturday 16 February 2019  22:46:15 -0800 (0:00:00.070)       0:00:00.070 ***** 
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sanswamy
<127.0.0.1> EXEC /bin/sh -c 'echo ~sanswamy && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823 `" && echo ansible-tmp-1550385975.94-217515337741823="` echo /home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/oracle/oci_instance.py
<127.0.0.1> PUT /home/sanswamy/.ansible/tmp/ansible-local-9350OltLNM/tmplDnBj9 TO /home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/ /home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py", line 113, in <module>
    _ansiballz_main()
  File "/home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_oci_instance_payload_ycCtKj/__main__.py", line 2026, in <module>
  File "/tmp/ansible_oci_instance_payload_ycCtKj/__main__.py", line 1966, in main
TypeError: 'unicode' object is not callable

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sanswamy/.ansible/tmp/ansible-tmp-1550385975.94-217515337741823/AnsiballZ_oci_instance.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_oci_instance_payload_ycCtKj/__main__.py\", line 2026, in <module>\n  File \"/tmp/ansible_oci_instance_payload_ycCtKj/__main__.py\", line 1966, in main\nTypeError: 'unicode' object is not callable\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
	to retry, use: --limit @/part1/work/cloud/ansible/ebs/ansible_cloudvm_layout/test_del_4.retry

PLAY RECAP ************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0  

A clear and concise description of what the issue is.

**Expected behavior**

**Environment**

* OS version:
OL7
* Ansible version:
2.7
    insert output of `ansible --version` here
ansible 2.7.0
  config file = /part1/work/cloud/ansible/ebs/ansible_cloudvm_layout/ansible.cfg
  configured module search path = [u'/home/sanswamy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul  3 2018, 06:28:28) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)]

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here
2.0.6

* OCI Ansible Modules version:

    insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here
1.2.0

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

  tasks:
  - name: Terminate/delete an instance
    oci_instance:
       id: ocid1.instance.oc1.phx.abyhqljrsoqeisk4gsnqrjmskhzxs7hef3wz7smtuc5obmstndyixzbuawga
       state: "absent"
    register: result
  - debug:
      msg: "{{result}}"

**Comment by debayan-gupta** [comment]
Thanks for using our modules. Looking at the example playbook, I am suggesting you to please ensure the id is in string format. The playbook should look like:

    name: Terminate/delete an instance
    oci_instance:
    id: "ocid1.instance.oc1.phx.abyhqljrsoqeisk4gsnqrjmskhzxs7hef3wz7smtuc5obmstndyixzbuawga"
    state: "absent"
    register: result
    debug:
    msg: "{{result}}"

Also, please refer to the 'Examples' section of the [documentation](https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_instance_module.html#oci-instance-module) for the delete/termination use case. You can refer to the 'Examples' of other modules also for guidance. Please let us know in case you face any additional issues.
