### ISSUE TITLE
oci_instance there is no option to specify boot volume size

### ISSUE THREAD

**Issue by skydreamerr** [oracle/oci-ansible-modules#33]
## Enhancement Report

**Describe the issue**
I can't specify boot disk size for an image in "source_details" parameter

**Comment by nalsaber** [comment]
We are working on it. It will be added in the coming release.

**Comment by gauravjain000** [comment]
This was released as part of the 1.7 release. 
https://github.com/oracle/oci-ansible-modules/blob/master/CHANGELOG.md

**Comment by gauravjain000** [comment]
@skydreamerr I am the product manager for Ansible module. Thanks for your feedback. If we have not connected before, I would love to do so understand 1. your usecase 2. how we can we make the experience better for you. I can be contacted on g.gaurav.j.jain@oracle.com.
Thanks,
Gaurav
