### ISSUE TITLE
oci_ad_facts always fetching domain of home region

### ISSUE THREAD

**Issue by saswamy** [oracle/oci-ansible-modules#34]
## Issue Report
Having tenancy with multiple region .
while using  "oci_ad_facts" to query domain - it always reports domain info of "Home" region . 
tried specifying region explicitly as below 
    region: "us-phoenix-1"
still it fetches domain of "ashburn" home region . 
 
**Describe the issue**
as above .

**Expected behavior**
When region is specified , module should ONLY report domain info fo that region alone .

**Environment**

* OS version:

* Ansible version:
2.7.0
    insert output of `ansible --version` here

* OCI Python SDK version:
2.2.1
* OCI Ansible Modules version:
1.6.0

**Ansible playbook to reproduce the issue**
  - name: Get Domain of Instance
    oci_ad_facts:
      config_file_location: "config_file_with_phoenic_regn_in_it"
      compartment_id: "ocid_for_compartment"
      region: "us-phoenix-1"
    register: result

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by manojmeda** [comment]
@saswamy I am not able to reproduce the issue. I am able to fetch the ADs for a non home region. Can you re-install the latest version of the oci modules and try the same again.

**Comment by saswamy** [comment]
Thank you Manoj . 
initially i tried reinstalling OCI modules and still had same issue . 
later uninstalled ansible, oci modules and python SDK and also deleted traces of files left out under site-packages . 
after that reinstalled everything - and then i see domain is getting picked up correctly .
