### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by subzero01** [oracle/oci-ansible-modules#35]
## Issue Report

If I try to install oci ansible on a clean ansible installation I get the following error:

Creating directory /usr/lib/python2.7/dist-packages/ansible/modules/cloud/oracle
Traceback (most recent call last):
File "./install.py", line 181, in
main()
File "./install.py", line 148, in main
os.mkdir(oracle_module_dir_path)
OSError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/ansible/modules/cloud/oracle'

A clear and concise description of what the issue is.

the parent directory of "oracle" is not existing. They should be created as well

Debian Linux 9

Ansible 2.2

* OS version:

* Ansible version:

ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/wolf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.3.0]

* OCI Python SDK version:

  not applicable here

* OCI Ansible Modules version:

  not applicable here

**Ansible playbook to reproduce the issue**

**Comment by subzero01** [comment]
#30 fixes the issue

**Comment by nalsaber** [comment]
@subzero01 I noticed you reopened the issue, do you still see this problem?

**Comment by nalsaber** [comment]
@subzero01 I will close the issue. Please let us know if you need any further help.
