### ISSUE TITLE
oci_object : not able to delete object in bucket

### ISSUE THREAD

**Issue by saswamy** [oracle/oci-ansible-modules#36]
## Issue Report
Have multi part objects - already available inside bucket on tenancy . 
From UI console , i am able to delete 1 or multiple objects by selecting them . 

with same credentials - when i use ansible module "oci_object" to delete the objects - it does NOT delete it .
play book run does not error and reports output in below format - which is different from what is documented .
Playbook code 
--------------------
    oci_object:
      namespace: "{{tenancy_name}}"
      bucket: "{{bucket_name}}"
      object: "file_chunk/2948297777/PTESTI/backuppiece/2019-02-28/0gtr1dbh_1_1/KTVs8w9V0wwD/0000000020"
      state: 'absent'

Sample Output : 
------------------------
 ok: [localhost] => (item={u'md5': u'0SR73+P0EtsnlW4uEtzN6A==', u'name': u'file_chunk/2948297777/PTESTI/backuppiece/2019-02-28/0gtr1dbh_1_1/KTVs8w9V0wwD/0000000020', u'time_created': u'2019-03-01T00:24:25.225000+00:00', u'size': 104857600})

Please advise .

**Describe the issue**
- Info same as above

**Expected behavior**
- objects should get deleted with the ansible module , when mentioned as "absent"  .

**Environment**
NA
* OS version:
NA
* Ansible version:

    insert output of `ansible --version` here

ansible 2.7.8
  config file = /part1/work/cloud/ansible/ansible.cfg
  configured module search path = [u'/home/sanswamy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul  3 2018, 06:28:28) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)]

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here
2.2.2
* OCI Ansible Modules version:

    insert output of `python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"` here
1.6.0
**Ansible playbook to reproduce the issue**

    oci_object:
      namespace: "{{tenancy_name}}"
      bucket: "{{bucket_name}}"
      object: "file_chunk/2948297777/PTESTI/backuppiece/2019-02-28/0gtr1dbh_1_1/KTVs8w9V0wwD/0000000020"
      state: 'absent'

**Comment by manojmeda** [comment]
Thanks @saswamy for reporting this. I am not able to reproduce the issue. Does this happen only with specific objects? Also can you please check if you can delete the same object using oci cli?

**Comment by saswamy** [comment]
Tried deleting same object (with OCI utility) which is NOT getting deleted via ansible module and with OCI utility deletion works as seen below : 


oci  --config-file /home/sanswamy/.oci/config  os object delete --bucket-name BUCKET_TEST  --object-name file_chunk/2948297777/PTESTI/backuppiece/2019-02-28/0gtr1dbh_1_1/KTVs8w9V0wwD/0000000020
Are you sure you want to delete this resource? [y/N]: Y

**Comment by saswamy** [comment]
Seems issue was with my ansible config. i was able to use ansible code to perform the deletion .
