### ISSUE TITLE
Facts are missing tags

### ISSUE THREAD

**Issue by tyskjohan** [oracle/oci-ansible-modules#37]
## Issue Report

**Describe the issue**

The fact scripts do not seem to return tags, making it hard to use together with dynamic inventory for infrastructure created through e.g. Terraform.

I.e. I am creating instances and volumes from Terraform, but I need to use ansible to actually mount them so I'd like to get data from facts to mount the right drive in the right place.

**Comment by manojmeda** [comment]
@tyskjohan Looks like the documentation is not updated but the tags are returned. We will update the documentation. But the `oci_instance_facts` module do return tags (both freeform and defined).
If you  do not see them, can you please provide the below information:

1) OCI ansible module version
2) Sample output of the fact module

**Comment by tyskjohan** [comment]
You are right. Looking forward to the update of the docs.
