### ISSUE TITLE
Question: Usage with cdb/pdb, not only oci

### ISSUE THREAD

**Issue by nalokin** [oracle/oci-ansible-modules#4]
## Question (not issue)

Is it possible to use this modules with the database instances (11.2, 12.1) as well as cdb/pdb for database user administration or this needs to be used only with Oracle Cloud Infrastructure? Was it tested?

I'm looking at this as a second option...
https://github.com/oravirt/ansible-oracle

Thanks.
-N.

**Comment by sivakumart** [comment]
Thanks @nalokin for your query.

The [`oci_database`](https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_database_module.html#oci-database-module), `oci_database_facts` and related oci_db_* modules can help provision, configure and manage [Oracle database service](https://docs.cloud.oracle.com/iaas/Content/Database/Concepts/databaseoverview.htm) in Oracle Cloud Infrastructure. These modules are not related to administrator or working with the Oracle database. As you had pointed, you could look at other community modules for that.

For further queries, please feel free to use other mechanisms discussed at https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/ansible.htm#questions to raise any questions that you may have with the https://github.com/oracle/oci-ansible-modules project.

Thanks
--Siva.
(Closing this as this is not an issue.)
