### ISSUE TITLE
Update version of Python SDK used 

### ISSUE THREAD

**Issue by priteshkp** [oracle/oci-ansible-modules#42]
## Issue Report

When following the getting started guide/screencast, I installed the OCI Python SDK (2.1.3), then the OCI Ansible module, and then tried to create and run a playbook.  This was all within a virtualenv environment with python 2.7.

**Expected behavior**

I expected to be able to run the playbook without a problem, but it ended up failing with:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named idna
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/pritpate/.ansible/tmp/ansible-tmp-1555613734.89-48392921355029/AnsiballZ_oci_ad_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/Users/pritpate/.ansible/tmp/ansible-tmp-1555613734.89-48392921355029/AnsiballZ_oci_ad_facts.py\", line 

This is fixed by "pip install idna", but a new user shouldn't have to do this.  The Python SDK fixed this issue in 2.1.5 - https://github.com/oracle/oci-python-sdk/issues/101.  The Ansible docs and screencast  (and depdendency) should be upgraded to use at least 2.1.5 to prevent new users from hitting this issue.

**Environment**

* OS version: Mac Sierra, 10.12.6

* Ansible version:

(ansible) pritpate-mac:playbooks pritpate$ ansible --version
ansible 2.7.10
  config file = None
  configured module search path = [u'/Users/pritpate/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pritpate/Documents/envs/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/pritpate/Documents/envs/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

* OCI Python SDK version:

(ansible) pritpate-mac:playbooks pritpate$ python -c "import oci;print(oci.__version__)"
2.1.3

* OCI Ansible Modules version:

(ansible) pritpate-mac:playbooks pritpate$ python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"
1.7.0

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by manojmeda** [comment]
@priteshkp Thanks for reporting this. Yes this is a known issue with oci sdk 2.1.3. We will update the minimum required version in the next release.
