### ISSUE TITLE
oci_service_gateway doc for 'services'  parameter is confusing

### ISSUE THREAD

**Issue by amykang2020** [oracle/oci-ansible-modules#44]
The OCI Service Gateway public documentation mentions using service cidr label  and the all service cidr label like "all-iad-services-in-oracle-services-networ" which is a service cidr label that represents all cidrs for the supported services.   The OCI Ansible oci_service_gateway module should allow specify these region specific all service cidr labels, such as "all-iad-services-in-oracle-services-network" or "all-phx-services-in-oracle-services-network", so that no need to enumerate a list of OCIDs for all available services when creating a service gateway for all services of the region.
please see "About Service CIDR Labels" section in
https://docs.cloud.oracle.com/iaas/Content/Network/Tasks/servicegateway.htm

The OCI console, on creating a service gateway,  allows to select "All \<region\> Services in Oracle Service Network" without the need to list each service's ocid.

**Comment by priteshkp** [comment]
Spoke to Amy offline -- there are not individual SGW service entries for every OCI service.  There is 1 SGW service that represents all OCI services.  You can use that 1 OCID now, and it will cover all existing and future services.

**Comment by amykang2020** [comment]
@priteshkp Thanks for the clarification.

**Comment by amykang2020** [comment]
Change this to a doc issue as the parameter 'services in the OCI Ansible module oci_service_gate way doc can lead to confusion as list of OCI service OCIDs
>services   List of the service OCIDs. These are the services that will be enabled on the service gateway.

**Comment by nalsaber** [comment]
@amykang2020 Ansible Modules follow the OCI APIs. 
The description of the `services` option in the API is: List of the OCIDs of the Service objects to enable for the service gateway.
https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/CreateServiceGatewayDetails

**Comment by nalsaber** [comment]
@amykang2020 Thanks for the feedback. Feel free to reach out to us in the future if you have any questions or improvements. I will close this issue.
