### ISSUE TITLE
oci_object upload with MemoryError (ansible 2.7.10)

### ISSUE THREAD

**Issue by zdudic** [oracle/oci-ansible-modules#47]
## Issue Report

Not able to upload 12G file (disk image) to Object storage. The playbook to list object files works well. Below inserted txt file has both playbooks.  

This is error while run upload playbook:

`The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible/tmp/ansible-tmp-1556749128.97-106775678342598/AnsiballZ_oci_object.py", line 113, in <module>
    _ansiballz_main()
  File "/tmp/ansible/tmp/ansible-tmp-1556749128.97-106775678342598/AnsiballZ_oci_object.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible/tmp/ansible-tmp-1556749128.97-106775678342598/AnsiballZ_oci_object.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_oci_object_payload_q5iRFa/__main__.py", line 357, in <module>
  File "/tmp/ansible_oci_object_payload_q5iRFa/__main__.py", line 343, in main
  File "/tmp/ansible_oci_object_payload_q5iRFa/__main__.py", line 258, in put_object
MemoryError

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible/tmp/ansible-tmp-1556749128.97-106775678342598/AnsiballZ_oci_object.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible/tmp/ansible-tmp-1556749128.97-106775678342598/AnsiballZ_oci_object.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible/tmp/ansible-tmp-1556749128.97-106775678342598/AnsiballZ_oci_object.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_oci_object_payload_q5iRFa/__main__.py\", line 357, in <module>\n  File \"/tmp/ansible_oci_object_payload_q5iRFa/__main__.py\", line 343, in main\n  File \"/tmp/ansible_oci_object_payload_q5iRFa/__main__.py\", line 258, in put_object\nMemoryError\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
`

**Expected behavior**

It's expected to have 12G file uploaded. 

**Environment**

From pip list:
oci             2.1.1
oci-cli         2.4.38

* OS version:
OL7

* Ansible version:

   ansible 2.7.10

* OCI Python SDK version:

    2.1.1

* OCI Ansible Modules version:

   1.3.0

**Ansible playbook to reproduce the issue**

   
[playbooks.txt](https://github.com/oracle/oci-ansible-modules/files/3136230/playbooks.txt)

**Comment by zdudic** [comment]
It works with jpg file 4k, is this Ansible issue or work around can be provided in this module.

**Comment by nalsaber** [comment]
@zdudic thanks for reporting this. This size of download was supported in newer SDK versions.
Please update OCI Python SDK (at least version 2.1.7 is needed)
$pip install --upgrade oci

Update to the latest version of Ansible Modules
https://github.com/oracle/oci-ansible-modules/releases

**Comment by nalsaber** [comment]
@zdudic is your error resolved?

**Comment by zdudic** [comment]
I believe yes. can be closed.
