### ISSUE TITLE
Installation fails on Macbook with python and ansible installed through Homebrew

### ISSUE THREAD

**Issue by arnoschots** [oracle/oci-ansible-modules#48]
## Issue Report

When I follow the official installation page for the oci ansible modules, the installation script fails on my MacBook Pro. Python/pip and ansible are installed through Homebrew. 

Error message: OCI Python SDK version-2.1.7 is required for using oci-ansible-modules. To install OCI Python SDK, use < pip install oci==2.1.7 >.

However oci is installed, see below.

A clear and concise description of what the issue is.

Installation script should work. I think it is caused by a "path" issue. The script uses the system wide installed python, pip & ansible, when not using virtualenv. It is not recognising the versions of python, pip and ansible installed through Homebrew.

**Environment**

* OS version:
Mac OS X 10.13.6

* Ansible version:

  2.7.10

* OCI Python SDK version:

note: when using:     `python -c "import oci;print(oci.__version__)"`  there is an error: 

"Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named oci"

"pip list" gives oci 2.2.7

* OCI Ansible Modules version:

 NA due to installation failure.

**Ansible playbook to reproduce the issue**

    NA due to installation failure

**Comment by nalsaber** [comment]
@arnoschots thanks for the feedback. You described the problem clearly. 
Your python installation can't find the OCI Python SDK which is needed by Ansible Modules. 
I would suggest using a virtual env as explained in the OCI Python SDK installation:
https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/installation.html

Once you confirm the OCI Python SDK is installed and recognized by python, you can remove the [section in the OCI Ansible modules installation script](https://github.com/oracle/oci-ansible-modules/blob/master/install.py#L73) that checks if OCI Python SDK exists in the installed_packages.

**Comment by arnoschots** [comment]
@nalsaber hi, thanks for your reply. I have installed everything in a virtual environment. That works flawless. I have the prerequisites installed system wide through brew and removed the parts of the installation checking as suggested above. Still the script fails with some path errors. Too much debugging, so I'll stick to using virtualenv. I am available for discussing this with the script writer.

**Comment by arnoschots** [comment]
ok, "fixed" it. I installed Ansible also though pip (although it was installed with Homebrew as well). Then ran the script with python3 as opposed to python. Modules installed successfully.

**Comment by nalsaber** [comment]
Great to hear that! Thanks for sharing the steps. I will close the issue.
