### ISSUE TITLE
Get the OCI ansible modules to work with instance credentials

### ISSUE THREAD

**Issue by tyskjohan** [oracle/oci-ansible-modules#54]
Currently, the scripts don't work with instance credentials. It would be great if that could be fixed.

**Comment by manojmeda** [comment]
@tyskjohan I am assuming you mean instance principal auth by instance credentials. If so, the oci modules support instance principal auth. Below the documentation for `auth_type` parameter(which is supported by all modules):

- auth_type
        The type of authentication to use for making API requests. By default `auth_type="api_key"' based authentication is performed and the API
        key (see `api_user_key_file') in your config file will be used. If this 'auth_type' module option is not specified, the value of the
        OCI_ANSIBLE_AUTH_TYPE, if any, is used. Use `auth_type="instance_principal"' to use instance principal based authentication when running
        ansible playbooks within an OCI compute instance.
        (Choices: api_key, instance_principal)[Default: api_key]

**Comment by tyskjohan** [comment]
I will have to try some more. I could not get it to work for the dynamic inventory script at least.

**Comment by tyskjohan** [comment]
It fails with the following (after managing to get some instances):

`oci_inventory.py --auth=instance_principal --debug
[...]
Building inventory for instance ocid1.instance.oc1.eu-frankfurt-1.abtheljsy7c4z4lkebgvdwq6s5op37nwnmd7ubxlezxxbhhyqotpwi5s6uaq
Traceback (most recent call last):
  File "/home/opc/oci-ansible-modules/inventory-script/oci_inventory.py", line 408, in __init__
    self.build_inventory()
  File "/home/opc/oci-ansible-modules/inventory-script/oci_inventory.py", line 1225, in build_inventory
    for instance in instances_by_region[region]
  File "/home/opc/oci-ansible-modules/inventory-script/oci_inventory.py", line 1049, in build_inventory_for_instance
    for key in instance.metadata:
TypeError: 'NoneType' object is not iterable

'NoneType' object is not iterable
`

**Comment by manojmeda** [comment]
@tyskjohan This could happen when the instance principal has only inspect permission on the instances in which case the instance metadata is not accessible. If so, can you please give read permission(instead of inspect) for instances and try?

**Comment by tyskjohan** [comment]
@manojmeda yes, that resolved the issue. Thanks a lot.
