### ISSUE TITLE
Add the support for OCI Resource Manager

### ISSUE THREAD

**Issue by neerkuma** [oracle/oci-ansible-modules#59]
## Issue Report
The OCI has release the OCI resource manager service a while ago. Please add the support in the oci-ansible module

**Comment by gauravjain000** [comment]
Hi, Can we talk about this in little more details? Please email me on g.gaurav.j.jain@oracle.com to take it forward.

**Comment by nalsaber** [comment]
This is added in our new modules: https://github.com/oracle/oci-ansible-collection/tree/master/plugins/modules
