### ISSUE TITLE
console connection for an OCI instance 

### ISSUE THREAD

**Issue by zdudic** [oracle/oci-ansible-modules#6]
Hi there, this is not issue, more like question or request for enhancement. I've been creating playbooks to list and create instances, works great, thanks.  
One thing I wasn't able to manage is to list console connection of existing instance, or to create a console connection for new instance, this will be very useful. Is there a plan to resolve this somehow?

**Comment by sivakumart** [comment]
Thanks @zdudic for raising this. Yes, we had planned to implement this earlier. We had assigned lower priority to Console Connection and History based modules in our earlier releases and couldn't get to that feature. We will implement this in the upcoming release.

**Comment by sivakumart** [comment]
@zdudic A new release [1.3.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.3.0) was posted today and that has support for Instance console connections and console history. Please try out the modules and share any feedback that you may have. Thanks.

- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_console_history_module.html#oci-console-history-module
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_instance_console_connection_module.html#oci-instance-console-connection-module

A sample is also available at
- https://github.com/oracle/oci-ansible-modules/tree/master/samples/compute/instance-console-connections-and-capture-console-history
