### ISSUE TITLE
oci_inventory.py not parsing the json defined-tags 

### ISSUE THREAD

**Issue by RanganathNangineni** [oracle/oci-ansible-modules#60]
The defined-tags option with the json formatted defined tags is not working with oci_inventory.py.

Error:
 ./oci_inventory.py --list --defined-tags {"xyz-applications":{"Lob":"xyz-mgmt"}}  --hostname-format private_ip

Expecting property name: line 1 column 2 (char 1)

**Comment by nalsaber** [comment]
@RanganathNangineni please escape the quotes char with backslash.
Ex: {\"xyz-applications\":{\"Lob\":\"xyz-mgmt\"}}
