### ISSUE TITLE
Add support for lifecycle policies on object storage buckets

### ISSUE THREAD

**Issue by rtaylor-coxauto** [oracle/oci-ansible-modules#63]
## Enhancement Request

The oci-bucket module does not provide the ability to set object lifecycle policies on a bucket.  Without this we have to manually add lifecycle policies after creating every bucket.  The Object Storage APIs provide Get/Delete/Put ObjectLifecyclePolicy methods that Ansible should be able to use.

**Comment by nalsaber** [comment]
@rtaylor-coxauto  Currently we don't have support for ObjectLifecyclePolicy in Ansible. We are working on adding the missing features. We will priorities adding support for ObjectLifecyclePolicy.

**Comment by nalsaber** [comment]
This is currently supported in release https://github.com/oracle/oci-ansible-modules/releases/tag/v1.11.0
