### ISSUE TITLE
Support for network security groups?

### ISSUE THREAD

**Issue by srflaxu40** [oracle/oci-ansible-modules#65]
Will network security groups be supported for things like `oci_instance` module?

**Comment by nalsaber** [comment]
@srflaxu40 Currently we don't support [Network Security Groups](https://docs.cloud.oracle.com/iaas/Content/Network/Concepts/networksecuritygroups.htm#api) in our modules. We are planning to add support for the missing services in the near future.

**Comment by srflaxu40** [comment]
Okay, thanks - any time frame? :)

**Comment by gauravjain000** [comment]
We are working on a project to significantly increase our coverage of OCI services. While it will help you and other customers significantly, by nature of the scope, this might take us several months to get there. 

We can possibly pick this up earlier in our sequence of taking up new service though. Could you please provide me little more details about your team? Which group do you represent and your use case? Feel free to send these details to me on g.gaurav.j.jain@oracle.com if you prefer that. 
We greatly appreciate your patience.

**Comment by srflaxu40** [comment]
Hi, @gauravjain000 will do.

**Comment by nalsaber** [comment]
@srflaxu40 Network Security Groups are currently supported in our latest release https://github.com/oracle/oci-ansible-modules/releases/tag/v1.12.0

**Comment by binhbaole** [comment]
How are security rules created with the module?
