### ISSUE TITLE
Enable oci_image.py to export a custom image to object storage

### ISSUE THREAD

**Issue by sdstewar** [oracle/oci-ansible-modules#66]
## Issue Report

**Describe the issue**

Currently this module only allows for creating/updating/importing a custom image.  It would be very helpful to be able to export a custom image to object storage .

**Expected behavior**

Be able to specify a custom image ID, bucket and object name and trigger the export of the custom image

**Environment**

* OS version: Ubuntu 18.04 LTS

* Ansible version:

ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sdstewar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]

* OCI Python SDK version: 2.2.19
* OCI Ansible Modules version: 1.10.0

**Ansible playbook to reproduce the issue**

N/A

**Comment by nalsaber** [comment]
Currently OCI Ansible modules don't support exporting exporting images to Object Storage. We are in the process of adding this support. It should be available soon.

**Comment by nalsaber** [comment]
This is currently supported in release 1.11.0 
Please use this module:
https://github.com/oracle/oci-ansible-modules/blob/master/library/oci_image_actions.py
