### ISSUE TITLE
oci_object_facts is returning unexpected values when partial object name matches

### ISSUE THREAD

**Issue by sdstewar** [oracle/oci-ansible-modules#67]
https://github.com/oracle/oci-ansible-modules/blob/3478e81b35b2158f5be460d84843d248e9f65b7c/library/oci_object_facts.py#L266

The documentation implies searching via object_name should be an exact match.  Instead objects where the name is contains a subset of the query is returned.  Expected behavior would be no items are returned.  

**Example**
```
  - name: Image exists
    oci_object_facts:
      namespace: "{{ aims_namespace }}"
      bucket: "{{ bucket_name }}"
      object_name: aims-ol7

ok: [localhost] => {
    "changed": false, 
    "objects": [
        {
            "md5": "bUXuJhKDedW+nFbqGG5LwQ==-16", 
            "name": "aims-ol76-190626", 
            "size": 5008404480, 
            "time_created": "2019-06-26T23:55:21.771000+00:00"
        }
   
```

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
