### ISSUE TITLE
oci_instance with key_by freeform_tags and instance-pool conflict

### ISSUE THREAD

**Issue by VAdamec** [oracle/oci-ansible-modules#68]
## Issue Report

After creating instance-pool I'm getting strange behaviour when trying to create new VM via oci_instance. Somehow instead new VM creation it will get VM from pool list. Some partial match happens ? 

```
TASK [Launch an instance test-demo-001 in KIHQ:US-ASHBURN-AD-1] ************************************************************************
ok: [localhost] => {
  "added_instances": [
    {
      "agent_config": {
        "is_monitoring_disabled": false
      },
      "availability_domain": "KIHQ:US-ASHBURN-AD-1",
      "compartment_id": "ocid1.compartment.oc1.xxxxxxx,
      "defined_tags": {},
      "display_name": "inst-instance-pool-20190815-1111",
      "extended_metadata": {
        "compute_management": {
          "instance_configuration": {
            "state": "SUCCEEDED"
          }
        }
      },
```

**Expected behavior**

No impact of pool config to oci_instance call should occur.

**Environment**

OL7

* Ansible version:

2.7.10

* OCI Python SDK version:

2.2.15

* OCI Ansible Modules version:

1.9.0

**Ansible playbook to reproduce the issue**

```- name: "Launch an instance {{ freetag_project }}-{{ freetag_role }}-{{ freetag_stage }}-{{ freetag_datacenter }}-{{ NMSET }} in {{ oci_ad }}-{{ ADSET }}"
      oci_instance:
        availability_domain: "{{ oci_ad }}-{{ ADSET }}"
        region: "{{ oci_region }}"
        compartment_id: '{{ oci_compartment_id }}'
        name: '{{ instance_fqdn }}'
        force_create: no
        key_by: freeform_tags
        source_details:
          source_type: image
          image_id: '{{ oci_image_ocid }}'
        shape: '{{ oci_shape }}'
        vnic:
            subnet_id: '{{ oci_subnet_ocid }}'
        metadata:
            ssh_authorized_keys: "{{ lookup('file', my_test_key ) }}"
        freeform_tags:
          test_fqdn: "{{ freetag_project }}-{{ freetag_role }}-{{ freetag_stage }}-{{ freetag_datacenter }}-{{ NMSET }}.test.com"
          test_short: "{{ freetag_project }}-{{ freetag_role }}-{{ freetag_stage }}-{{ freetag_datacenter }}-{{ NMSET }}"
          test_project_role_stage: '{{ freetag_project }}-{{ freetag_role }}-{{ freetag_stage }}'
          test_shape: '{{ oci_shape }}'
          test_owner: '{{ VM_OWNER }}'
        preserve_boot_volume: no
      register: result
```

**Comment by nalsaber** [comment]
@VAdamec  It seems that the module is partially matching the name instance name and returning it. Can you please use -vvv when you run the module and share the sent values to create the instance? I am interested in knowing the value of the variable: instance_fqdn.

**Comment by manojmeda** [comment]
@VAdamec I noticed that you are using `key_by: freeform_tags` when you are creating an instance. When `key_by` is specified, we only match the given parameters (in this case `freeform_tags`) to find a matching existing resource. Does the instances created by the instance pool has the same freeform tags as this instance?

Either you could remove `key_by` and try creating the instance, in which case we would match all the mentioned instance parameters (except freeform tags) to find if a matching instance exists.
Or you could give more parameters in `key_by` to get a good match. For ex: key_by: [display_name, availability_domain, compartment_id, shape].

**Comment by VAdamec** [comment]
It could be my misunderstanding of key_by, `key_by: [display_name, availability_domain, shape]` seems to work, what I want is like `key_by: [test_fqdn, test_shape]` eg use my own freeform tags but `key_by: freeform_tags` seems to try match freeform_tags word/paramter  which is not defined and then it could mislead search/match.

**Comment by manojmeda** [comment]
@VAdamec `key_by` is actually a list. Can you try `key_by: ["freeform_tags"]` instead of `key_by: freeform_tags`.

**Comment by manojmeda** [comment]
@VAdamec Hope the suggestion worked for you. I am closing this issue. Please feel free to reopen if you are still facing any issue.
