### ISSUE TITLE
Enhancement request to return IP addresses of 'Mount Targets' and 'DB Systems'

### ISSUE THREAD

**Issue by joshmullis** [oracle/oci-ansible-modules#71]
## Issue Report

Requesting an enhancement to easily retrieve the IP addresses for 'Mount Target' and 'DB System' resources.  (This was recently done with the 'oci_instance_facts' module) 

**Expected behavior**

- oci_mount_target_facts returns the actual IP address instead of just the private_ip_ids, which requires another lookup

- oci_db_system_facts returns the actual scan/vip IP addresses instead of just the ids, which requires another lookup

- oci_db_node_facts returns the actual private IP address instead of just the vnic_id, which requires another lookup

**Comment by tyskjohan** [comment]
+1

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
