### ISSUE TITLE
Docs indicate you can filter by display_name but that's not true

### ISSUE THREAD

**Issue by sdstewar** [oracle/oci-ansible-modules#72]
The [module documentation ](https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_image_facts_module.html#oci-image-facts-module) indicates that _display_name_ is a parameter that may be used to filter image results, but it is actually not used it all in the current code.  

Adding the option below the referenced line produces an error that _display_name_ must be the only option.  When this condition is met it works, though the docs imply this is can be used with other filters.

https://github.com/oracle/oci-ansible-modules/blob/3478e81b35b2158f5be460d84843d248e9f65b7c/library/oci_image_facts.py#L188

**Comment by nalsaber** [comment]
Can you please provide your playbook?

**Comment by nalsaber** [comment]
This is a bug. We will fix it in the future. 
I replicated it using this test:
oci_image_facts:
        compartment_id: "..."
        display_name: "XXX"

**Comment by sdstewar** [comment]
Thank you!  My apologies for not responding, I was away for a few days.

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
