### ISSUE TITLE
Unable to location option for device path and Size for block volume

### ISSUE THREAD

**Issue by psaini79** [oracle/oci-ansible-modules#73]
## Did not find block volume name and size parameter

**I am using oci-ansible-modules/samples/block_volume/attach_connect_block_volume/sample.yaml but unable to locate the option to add device path for udev naming convention. Also, did not find option to specify the size of block device**

**Environment**

* OS version: OEL 7.4

* Ansible version: 2.6.4

 `ansible 2.6.4
  config file = None
  configured module search path = ['/home/oci/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.3 (default, Feb  8 2018, 05:35:00) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
` 

* OCI Python SDK version:

   `2.3.2`

* OCI Ansible Modules version:

 `1.10.0`

**Ansible playbook to reproduce the issue**

     oci-ansible-modules/samples/block_volume/attach_connect_block_volume/sample.yaml

**Comment by psaini79** [comment]
Ok. I can see size_in_gbs ansible-doc oci_volume command but unable to locate to specify the device path.

**Comment by nalsaber** [comment]
@psaini79 
size_in_gbs is in oci_volume
Device path is currently missing from our modules. It will be added in `volume_attachment` as `device`. This can take few weeks.

**Comment by nalsaber** [comment]
This has been added in release [v1.13.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.13.0)
