### ISSUE TITLE
OCI_SUBNET tries to recreate existing Subnet : Error

### ISSUE THREAD

**Issue by psaini79** [oracle/oci-ansible-modules#74]
## Issue Report

**oci_subnet module does not use existing subnet and tries to re-create**

I created the compute using oci-ansible-modules/samples/compute/launch_compute_instance/main.yaml  and again trying to create the compute. I changed the required values related to instance name and share. However, it is failing for the same subnet as I have not changed the subnet and I want instance to be created  under the same subnet. 

**Expected behavior**
Technically, this operation must be idempotent and if the subnet exist in the VCN , it should not report any error.

**Environment**

* OS version:
Oracle Linux Server release 7.4
* Ansible version:
ansible 2.6.4
  config file = None
  configured module search path = ['/home/psaini/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.3 (default, Feb  8 2018, 05:35:00) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

    insert output of `ansible --version` here

* OCI Python SDK version:

    insert output of `2.3.2` here

* OCI Ansible Modules version:

    insert output of `1.10.0` here

**Ansible playbook to reproduce the issue**

    oci-ansible-modules/samples/compute/launch_compute_instance/main.yaml

- name: Create a subnet to host the public instance. Link security_list and route_table.
  oci_subnet:
    availability_domain: "{{ instance_ad }}"
    cidr_block: "{{ subnet_cidr }}"
    compartment_id: "{{ instance_compartment }}"
    display_name: "{{ subnet_name }}"
    prohibit_public_ip_on_vnic: false
    route_table_id: "{{ rt_id }}"
    security_list_ids: [ "{{ instance_security_list_ocid }}" ]
    vcn_id: '{{ vcn_id }}'
    dns_label: "{{ subnet_dns_label }}"
  register: result
- set_fact:
    instance_subnet_id: "{{ result.subnet.id }}"

**Comment by psaini79** [comment]
TASK [oci-launch-compute : set_fact] **********************************************************************************************************************
ok: [localhost]

TASK [oci-launch-compute : Create a subnet to host the public instance. Link security_list and route_table.] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "{'status': 400, 'message': u'The requested CIDR 172.16.1.0/24 is invalid: subnet ocid1.subnet.oc1.phx.aaaaaaaasxnho46usys2j4ibw7jgytji22dpza624cbbzrs476lftpqxc3qa with CIDR 172.16.1.0/24 overlaps with this CIDR.', 'code': u'InvalidParameter', 'opc-request-id': '57429568EE5943E5A7E4A396B683E823/BE945BF2F2356020E38E495BDE46F5D4/8D6B7A966B75AF9C9014EED2550E5D50'}"}

PLAY RECAP ************************************************************************************************************************************************
 Dynamic Host IP xx.xx.xx.xx : ok=26   changed=22   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
localhost                  : ok=54   changed=15   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

(airflow_on_oke) [julian@jtower-home airflow-on-oke]$ ansible-playbook oci_launch_compute_with_block_devices.yamlcd roles/
lERROR! the playbook: oci_launch_compute_with_block_devices.yamlcd could not be found
(airflow_on_oke) [julian@jtower-home airflow-on-oke]$ lls

Sent from my iPhone

**Comment by nalsaber** [comment]
Thanks for reporting. We will look into it.

**Comment by psaini79** [comment]
@nalsaber 

Any update on this?

**Comment by manojmeda** [comment]
@psaini79 The subnet module matches the existing values with the values provided in the playbook. Looks like some parameter is not matching which is causing the ansible module to create the subnet again. Can you please check if some property has changed for the subnet after it is created. For ex: any additional security lists added etc. Also can you check if some defined tags were added to the subnet after its creation.

**Comment by psaini79** [comment]
@manojmeda 

I have not changed anything in the file, it tries to recreate subnet and fails.

**Comment by manojmeda** [comment]
@psaini79 Sorry for the delayed response. 

Can you provide us the debug log for the second run. You can enable the debug log by setting the environment variable `export LOG_LEVEL=DEBUG`

Also subnet details by running the below command:

`ansible localhost -m oci_subnet_facts -a 'subnet_id=ocid1.subnet.oc1.iad.aaaaaaaamcixxxxxxxxxx'`

Note: Please hide any sensitive information like OCIDs which providing the output.

**Comment by manojmeda** [comment]
@psaini79 Closing the ticket. Please reopen the ticket if you are still facing this issue.
