### ISSUE TITLE
Unable to create "Always Free" ADW/ATP Database

### ISSUE THREAD

**Issue by jufrey** [oracle/oci-ansible-modules#77]
I tried to create an "always free" ADW/ATP database. I do not find a licensing option or anything similar therefore I tried to create the database with the limits for ADW/ ATP but I got following errors.

Task:
  - name: Create a new Autonomous Database
    oci_autonomous_data_warehouse:
        compartment_id: "{{ compartment_ocid }}"
        cpu_core_count: "1"
        display_name: "{{ display_name }}"
        admin_password: "{{ admin_password }}"
        db_name: "{{ db_name }}"
        data_storage_size_in_tbs: "0.02
        license_model: "BRING_YOUR_OWN_LICENSE"
        state: 'present'
    register: result

Error:
{'status': 400, 'message': u'The minimum Autonomous Data Warehouse dataStorageSizeInTBs is 1.', 'code': u'InvalidParameter', 'opc-request-id': '34A78130BBD742B0BE2E3D0E21A5E858/BC9AB3A455B209A3A923816C87FF101F/04F3FD81DA528B6BC51EC8EC9AAF7E98'}

Please let me know if you need further information.

**Comment by mross22** [comment]
Hi @jufrey in order to launch an always free ADW/ATP database you need to specify the isFreeTier parameter to the API which is not yet supported in Ansible since this functionality was recently released in the services.

**Comment by mross22** [comment]
This has been added in release [v1.13.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.13.0)
