### ISSUE TITLE
oci_policy Module - Update removing existing statements

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-ansible-modules#78]
## Issue Report

**Describe the issue**
Currently we are updating new statements to an existing policy using oci_policy Module, but we are observing that existing statements are being removed and adding the new one. How to prevent removing/purging the existing statements of respective policy?

**Expected behavior**
it should not purge existing statements of a policy.

**Environment**

* OS version: OL7.7

* Ansible version: 
ansible 2.7.9
  config file = /home/vburamdo/obsolete/tst_mgmt/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 08:19:52) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]

* OCI Python SDK version:

2.5.0

* OCI Ansible Modules version:

1.10.0

**Ansible playbook to reproduce the issue**

[update_policy.txt](https://github.com/oracle/oci-ansible-modules/files/3680578/update_policy.txt)

**Comment by manojmeda** [comment]
@vburamdo Ansible modules depend on OCI SDK/API and this is the current behaviour of the API. You could workaround this by fetching the existing rules first and appending new rules to it and then use the new list of statements to update the policy. Would this approach work for you case?

**Comment by vburamdo** [comment]
@manojmeda we have many tenancy's and we wanted this to update on some tenancy's only based on group_vars. Can we have feature like purge_statements: no something like this?

**Comment by manojmeda** [comment]
@vburamdo We try to keep ansible modules as close as possible to the API. But this looks like a useful enhancement. We will review and let you know.

**Comment by vburamdo** [comment]
@manojmeda  thanks for the update, please advice when this new feature would be available.

**Comment by vburamdo** [comment]
@manojmeda  can you please advice when this new feature would be available.

**Comment by manojmeda** [comment]
The legacy OCI Ansible modules have been deprecated in favor of the new [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection). These are no longer supported and there will be no further updates or fixes. Please migrate to the [OCI Ansible collection](https://github.com/oracle/oci-ansible-collection) for improved features and continued support. Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best practices.
