### ISSUE TITLE
oci_swift_password is reporting the password as null during the creation

### ISSUE THREAD

**Issue by neerkuma** [oracle/oci-ansible-modules#8]
## Issue Report

A clear and concise description of what the issue is.
The oci_swift_password is reporting the password as null during the creation, and if it oci_swift_password can be rename to auth token as its been renamed to auth token. 
ansible playbook output 
    "swift_password": {
        "description": "swift password",
        "expires_on": null,
        "id": "ocid1.credential.oc1.XXXXXXXXXXXXXXXX",
        "inactive_status": null,
        "lifecycle_state": "ACTIVE",
        "password": null,
        "time_created": "2018-11-05T11:43:27.935000+00:00",
        "user_id": "ocid1.user.oc1..XXXXXXXXXXXXXXXXXXX"
    }

It should display the token/password one time during the creation.

* Ansible version:

  ansible 2.6.4

* OCI Python SDK version:

   2.0.3

* OCI Ansible Modules version:
1.1.0

**Ansible playbook to reproduce the issue**

---
- name : Create swift auth token
  connection: local
  hosts: localhost
  tasks:
    - name: Create a new swift password
      oci_swift_password:
         user_id: "ocid1.user.oc1..XXXXXXXXXXXX"
         description: "swift password"
      register: result

    - name: Dump result
      debug:
        msg: '{{result}}'

**Comment by sivakumart** [comment]
Thanks @neerkuma for raising this. Yes, this appears to be a bug. It appears that the Swift Password API has recently changed to only return the password during creation. The module was attempting a GET after the resource was created, and returning the result. We will fix this logic in the next release of OCI ansible modules. 

We were also planning to add support for Auth token management in OCI's IAM service in the upcoming release in the next few days. Please stay tuned, and thanks again for raising this issue.

**Comment by sivakumart** [comment]
@neerkuma A new release [1.3.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.3.0) was posted today and this has fixed this bug. 
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_swift_password_module.html

This release also includes modules for Auth token management. Please check out
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_auth_token_module.html
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_auth_token_facts_module.html

Please try out the modules and share any feedback that you may have. Thanks.
