### ISSUE TITLE
Ansible Module to upload image to OCIR

### ISSUE THREAD

**Issue by psaini79** [oracle/oci-ansible-modules#83]
## Issue Report

Is there a ansible module to upload docker images to OCIR?

A clear and concise description of what the issue is.

I did not find a way to upload images to OCIR using OCI ansible modules. We should have a module to upload the docker images to OCIR.

**Environment**

* OS version: OEL 7.x

* Ansible version:

    insert output of `ansible 2.8.4` here

* OCI Python SDK version:

    insert output of `2.5.2` here

* OCI Ansible Modules version:

    insert output of `python -c "1.10.0` here

**Comment by manojmeda** [comment]
@psaini79 There is no API support for uploading images to the registry. Refer https://docs.cloud.oracle.com/iaas/api/#/en/containerengine/20180222/. Ansible modules require API to be available. We will have the module when API adds support for it.

**Comment by sivakumart** [comment]
@psaini79 OCIR supports the Docker V2 API and so you should be able to use the built-in docker ansible modules `docker_login` (https://docs.ansible.com/ansible/latest/modules/docker_login_module.html) and `docker_image` (https://docs.ansible.com/ansible/latest/modules/docker_image_module.html) to login and push your docker image to OCIR. Please refer https://docs.cloud.oracle.com/iaas/Content/Registry/Tasks/registrypushingimagesusingthedockercli.htm for instructions on docker credentials for the login.
