### ISSUE TITLE
Ansible on 2nd and later runs expanding the Logical Volume size by doubling it, rather than locking it at 50% of the VG for Shape VMDENSEIO2.16

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-ansible-modules#84]
## Issue Report

**Describe the issue**
Issue is caused by Ansible on 2nd and later runs expanding the Logical Volume size by doubling it, rather than locking it at 50% of the VG for the Shape VMDENSEIO2.16
[sample_vmdenseIO2_16.txt](https://github.com/oracle/oci-ansible-modules/files/3756014/sample_vmdenseIO2_16.txt)

**Expected behavior**
It should be locking it at given 50% of the VG and it shouldn't be expanding the Logic Volume size.

**Environment**

* OS version: OracleLinux 7.x

* Ansible version:

 ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 08:19:52) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]

* OCI Python SDK version:

2.6.0

* OCI Ansible Modules version:

1.11.0

**Ansible playbook to reproduce the issue**

[sample_vmdenseIO2_16.txt](https://github.com/oracle/oci-ansible-modules/files/3756021/sample_vmdenseIO2_16.txt)

**Comment by vburamdo** [comment]
====================================================
first-run:
====================================================
[root@vmdenseio216-test ~]# df -hP /nvme
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/vg_nvme-lv_nvme  3.0T   33M  3.0T   1% /nvme
[root@vmdenseio216-test ~]# vgs
  VG      #PV #LV #SN Attr   VSize  VFree
  vg_nvme   2   1   0 wz--n- 11.64t 5.82t
[root@vmdenseio216-test ~]# lvs
  LV      VG      Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_nvme vg_nvme rwi-aor--- 2.91t                                    0.52
[root@vmdenseio216-test ~]# pvs
  PV             VG      Fmt  Attr PSize PFree
  /dev/nvme0n1p1 vg_nvme lvm2 a--  5.82t 2.91t
  /dev/nvme1n1p1 vg_nvme lvm2 a--  5.82t 2.91t
[root@vmdenseio216-test ~]#

====================================================
second-run:
====================================================
[root@vmdenseio216-test ~]# df -hT /nvme
Filesystem                  Type  Size  Used Avail Use% Mounted on
/dev/mapper/vg_nvme-lv_nvme xfs   5.9T   33M  5.9T   1% /nvme
[root@vmdenseio216-test ~]# vgs
  VG      #PV #LV #SN Attr   VSize  VFree
  vg_nvme   2   1   0 wz--n- 11.64t    0
[root@vmdenseio216-test ~]# lvs
  LV      VG      Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_nvme vg_nvme rwi-aor--- 5.82t                                    0.51
[root@vmdenseio216-test ~]# pvs
  PV             VG      Fmt  Attr PSize PFree
  /dev/nvme0n1p1 vg_nvme lvm2 a--  5.82t    0
  /dev/nvme1n1p1 vg_nvme lvm2 a--  5.82t    0
[root@vmdenseio216-test ~]#

**Comment by vburamdo** [comment]
ansible not able to deal with 2 block devices using LVM in RAID1/Mirror while 4 block devices using LVM in RAID10/Striple + Mirror works fine.

**Comment by nalsaber** [comment]
Hi @vburamdo, the modules you are using in your playbook are from Ansible and they are not related to our cloud modules. If you have problems with the Logical Volume size, I think it is best to contact the OCI block storage service team for questions:
https://docs.cloud.oracle.com/iaas/Content/GSG/Tasks/contactingsupport.htm

**Comment by vburamdo** [comment]
@nalsaber  thanks for the update. We will check with them.

**Comment by vburamdo** [comment]
We have tried in ansible 2.9.7 versions too, its not locking it at 50% of the VG for second and later runs.

----------
First Run:
----------

[root@vmdenseio216 ~]# df -hP /nvme/
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/vg_nvme-lv_nvme  3.0T   33M  3.0T   1% /nvme
[root@vmdenseio216 ~]# vgs
  VG      #PV #LV #SN Attr   VSize  VFree
  vg_nvme   2   1   0 wz--n- 11.64t 5.82t
[root@vmdenseio216 ~]# pvs
  PV             VG      Fmt  Attr PSize PFree
  /dev/nvme0n1p1 vg_nvme lvm2 a--  5.82t 2.91t
  /dev/nvme1n1p1 vg_nvme lvm2 a--  5.82t 2.91t
[root@vmdenseio216 ~]# lvs
  LV      VG      Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_nvme vg_nvme rwi-aor--- 2.91t                                    0.33
[root@vmdenseio216 ~]#

=====
----------
Second Run:
----------

[root@vmdenseio216 ~]# df -hP /nvme/
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/vg_nvme-lv_nvme  5.9T   33M  5.9T   1% /nvme
[root@vmdenseio216 ~]# vgs
  VG      #PV #LV #SN Attr   VSize  VFree
  vg_nvme   2   1   0 wz--n- 11.64t    0
[root@vmdenseio216 ~]# lvs
  LV      VG      Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_nvme vg_nvme rwi-aor--- 5.82t                                    0.54
[root@vmdenseio216 ~]#
