### ISSUE TITLE
Allow enable of In Transit Encryption for Boot Volumes when creating Instances

### ISSUE THREAD

**Issue by rtaylor-coxauto** [oracle/oci-ansible-modules#87]
## Issue Report

The oci_instance module does not allow you to specify that In Transit Encryption for boot volumes when creating a new instance.  

**Expected behavior**

Add an option in the oci_instance.py module to allow creation of an instance with "Use in-transit encryption" enable.d

**Environment**

* OS version:

n/a

* Ansible version:

n/a

* OCI Python SDK version:

n/a

* OCI Ansible Modules version:

n/a

**Ansible playbook to reproduce the issue**

n/a

**Comment by nalsaber** [comment]
Thank you for reporting this. We are working on building new modules that will support all of the missing features. They should be released in the coming few months.

**Comment by nalsaber** [comment]
This is available in our new modules: https://github.com/oracle/oci-ansible-collection/
