### ISSUE TITLE
Need to be allowed to specify a device path when attaching block volumes to instances

### ISSUE THREAD

**Issue by rtaylor-coxauto** [oracle/oci-ansible-modules#88]
## Enhancement Request

The oci_volume_attachment module does not allow the device path to be specified when attaching a block volume to an instance.

**Expected behavior**

The oci_volume_attachment module will provide a "device_path" or "device" option.  The module already returns the "device" in the return dict.

**Environment**

n/a

* OS version:

n/a

* Ansible version:

2.8+

* OCI Python SDK version:

n/a

* OCI Ansible Modules version:

n/a

**Ansible playbook to reproduce the issue**

n/a

**Comment by nalsaber** [comment]
Thanks for reporting this. We will add this field with the coming release next month.

**Comment by mross22** [comment]
This has been added in release [v1.13.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.13.0)
