### ISSUE TITLE
DB Home patching precheck operation using ansible modules is inconsistent with OCI-CLI and OCI console

### ISSUE THREAD

**Issue by rishimahajan** [oracle/oci-ansible-modules#89]
## Issue Report

**Describe the issue**
Database Home patching precheck operation is inconsistent with OCI-CLI and OCI console.
Ansible Module behavior - A re-run of precheck operation on a database home **skips the precheck** execution when first run is successful.
OCI Console behavior - A re-run of precheck operation on a database home **re-runs the prechec**k execution when first run is successful.
OCI CLI behavior - A re-run of precheck operation on a database home **re-runs the precheck** execution when first run is successful.

**Expected behavior**
Same as OCI console and OCI-CLI.Ansible module behaviour is required to be made consistent with OCI Console and CLI behavior.

```

**Environment**

* OS version:
Oracle Linux Server release 7.7

* Ansible version:
ansible 2.8.4
  config file = /home/opc/dbpatching/ansible.cfg
  configured module search path = [u'/home/opc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 08:19:52) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]

* OCI Python SDK version:
2.6.5

* OCI Ansible Modules version:
1.12.0
```
**Ansible playbook to reproduce the issue**

```
Using Ansible Modules
- name: Run PRECHECK for "{{ db_patch_description }}" with patch id "{{ db_patch_id }}" on database home
  oci_db_home:
    db_home_id: "{{ db_home_ocid }}"
    patch_details:
      patch_id: "{{ db_patch_id }}"
      action: 'PRECHECK'
    state: 'present'

Using OCI-CLI
[opc@anstwr dbpatching]$ oci db  database patch --database-id "ocid1.database.oc1.iad.abuwcljtrgv4ue76l6qlrsn2lzdxsrrqai4lkeqjgchftiydd3hhin2ywjva" --patch-action 'PRECHECK' --patch-id "ocid1.dbpatch.oc1.iad.abuwcljtgyhwg5dk6k53wqfv6lqdbd3qvlxilcmrbfq5ah3hqvnc5z5x2wga"

Using OCI-Console
DB System ---> Databases ---> Patches ---> Precheck
```

**Comment by nalsaber** [comment]
Fix is released in version [1.14.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.14.0)
