### ISSUE TITLE
Please add the NAT gateway support in the ansible

### ISSUE THREAD

**Issue by neerkuma** [oracle/oci-ansible-modules#9]
A clear and concise description of what the issue is.
This is enhancement request for the NAT gateway. The OCI NAT gateway was released in last month, please add the NAT gateway support in the ansible.
 
Ansible version:

ansible 2.6.4

OCI Python SDK version:

2.0.3

OCI Ansible Modules version:
1.1.0

**Comment by sivakumart** [comment]
Thanks @neerkuma for your suggestion. This is coming in the upcoming release (should be available in the next few days). Thanks.

**Comment by sivakumart** [comment]
@neerkuma A new release [1.3.0](https://github.com/oracle/oci-ansible-modules/releases/tag/v1.3.0) was posted today and this has added support for NAT gateways.

- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_nat_gateway_module.html
- https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_nat_gateway_facts_module.html

Please try out the modules and share any feedback that you may have. Thanks.
