### ISSUE TITLE
Enable Shared Read/Write Volume Attachment

### ISSUE THREAD

**Issue by rtaylor-coxauto** [oracle/oci-ansible-modules#96]
## Issue Report

The oci volume attachment does not allow for the creation of shared read/write volume attachments. 

**Expected behavior**

A call to oci volume attachment with state:present allow the creation of shared read/write or share read only volume attachments.

**Environment**

* OS version: OEL 7.x

* Ansible version:

Current

* OCI Python SDK version:

Current

* OCI Ansible Modules version:

New

**Comment by AmeyaLokre** [comment]
This has been fixed in release v1.16.0
